### ISSUE TITLE
TagID is not correct 

### ISSUE THREAD

**Issue by Terminus80** [whitedogg13/react-native-nfc-manager#104]
The TagId return in reverse mode.
Example: 
 Real tagId is:  E0040108136EF522
 react-native-nfc-manager RETURN 22F56E13080104E0.
 the bugs is in **bytesToHex** function.

**Comment by whitedogg13** [comment]
Hi, I don't understand the issue exactly, from our side we can verify the tag id is correct, ex: compare the result with NXP Tag Info app. Maybe you can be more explicit about the error?

**Comment by poison** [comment]
Hi @Terminus80 what kind of tag did you use? We need more information in order to investigate this. Please let us know if you found a work-around as well. Thanks!

**Comment by whitedogg13** [comment]
close due to no further activities.
