### ISSUE TITLE
NfcManager.onStateChange callback is executed only if NfcManager.start is called before

### ISSUE THREAD

**Issue by filippoitaliano** [whitedogg13/react-native-nfc-manager#105]
Is this the expected behaviour? I would like to use `NfcManager.onStateChange` when the NFC is caught disabled (with `NfcManager.isEnabled`) during app initialization. In such case I prompt the user to enable it and I try to re-start the service immediatly after `NfcManager.onStateChange` catch the enabling event. Is this possible without manually call and handle the rejection of `NfcManager.start` before the `NfcManager.onStateChange` call?

Thanks in advance!

**Comment by whitedogg13** [comment]
Yes, it's the expected behavior, we do want the `NfcManager.start` is called before any other methods in this library. It is a safe operation even if the NFC is disabled.

**Comment by filippoitaliano** [comment]
Ok, got it.
