### ISSUE TITLE
Add Support for Ultralight

### ISSUE THREAD

**Issue by sahaya4us** [whitedogg13/react-native-nfc-manager#106]
I have used [react-native-nfc-manager](https://github.com/whitedogg13/react-native-nfc-manager) in my react native project to read NFC tags.

But I am not able to read Ultralight tags.  It seems, It is not supported yet.  Could you please add Ultralight tag support, as most of the devices in my country uses [MifareUltralight](https://www.mifare.net/en/products/chip-card-ics/mifare-ultralight/) . If this library support [MifareUltralight](https://www.mifare.net/en/products/chip-card-ics/mifare-ultralight/) it will be more helpful to the NFC  community.

**Comment by subrajits** [comment]
+1 for Ultralight support request

**Comment by sahaya4us** [comment]
Hi @whitedogg13 , Thank you so much. It is working perfectly for [mifare-ultralight-support](https://github.com/whitedogg13/react-native-nfc-manager/tree/mifare-ultralight-support).

**Comment by whitedogg13** [comment]
Thanks for feedback! We will merge it into master and release soon.

**Comment by whitedogg13** [comment]
Hi, we have published v1.1.0 to support `MifareUltralight` officially, thanks for contributing!
