### ISSUE TITLE
fatal error: 'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by suraj-shanbhag** [whitedogg13/react-native-nfc-manager#110]
Hi , i'am getting this error when I try to build in ios ,Android works fine
![screen shot 2018-11-07 at 12 17 17 pm_censored](https://user-images.githubusercontent.com/21170260/48115165-ee396000-e287-11e8-8952-1d95e1fd5974.jpg)
I have followed this order:
- npm i --save react-native-nfc-manager 
- react-native link react-native-nfc-manager
- setup Capabilities,Plist
- Pod install
My React version is "16.4.1" and RN version:"0.55.4"

**Comment by whitedogg13** [comment]
Hi, thanks for reporting this issue. Can you try it again without using Pod?

**Comment by christianchown** [comment]
@suraj-shanbhag have you recently upgraded React Native? I often get these kind of errors when I do, and they are all false negatives.

Try the following from the root of your project to clear all your directories and caches and reinstall your libraries
```
rm -rf node_modules
rm -rf ~/.rncache
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -rf ~/Library/Caches/CocoaPods
rm -rf ios/CocoaPods
yarn cache clean     # or npm cache clean --force
yarn                 # or npm install
cd ios
pod install
```

If that doesn't work, go into Xcode and go Project->Scheme->Edit scheme of your project, go to "Build" and untick Parallelize Build. (You can reenable it once you're building again)

**Comment by whitedogg13** [comment]
close due to no further activities
