### ISSUE TITLE
fail to connect tag

### ISSUE THREAD

**Issue by GreatAuk** [whitedogg13/react-native-nfc-manager#119]
When I run your [example](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/AndroidTechTestNdef.js) , I get a tag like:
`{
id: "9F77E3A7"
techTypes: ["android.nfc.tech.IsoDep", "android.nfc.tech.NfcA"]
}`
and a warning of 'fail to connect tag'

**Comment by whitedogg13** [comment]
Hi, @GreatAuk , that is because the tag doesn't have the `Ndef` technology, as listed in the `techTypes`. So the library can detect the tag, but cannot connect it using `Ndef` technology type.

Thanks!

**Comment by GreatAuk** [comment]
Thank you for your reponse😁
