### ISSUE TITLE
Native Module cannot be null in iOS simulator

### ISSUE THREAD

**Issue by milon87** [whitedogg13/react-native-nfc-manager#12]
can we run in the simulator?
![screen shot 2017-11-23 at 12 56 43 pm](https://user-images.githubusercontent.com/3435314/33161455-cbe40d68-d04d-11e7-90e6-13cfbd215f33.png)

**Comment by whitedogg13** [comment]
Hi, thanks for spotting this. I will check it out and get back soon.

**Comment by whitedogg13** [comment]
Hi, I have tested against iOS simulator for both 9.3+iPhone6 and 11.0+iPhone8, and none of them throw such errors.

By looking into your error stack trace above, have you ever run `react-native link react-native-nfc-manager` to link the native module? It looks like that you're missing native module^^

**Comment by milon87** [comment]
yes, I have linked. in android, it works perfectly.

**Comment by whitedogg13** [comment]
Can you check if the ios project is properly linked?
1. the library project has been added into your `Libraries` group
2. the static lib `libNfcManager.a` should show in the `Build Phases -> Link Binary With Libraries` section.

If they are not appeared, you can manually link this library for now by following this instruction: https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by milon87** [comment]
the problem is here. anything I missing?

<img width="775" alt="screen shot 2017-11-28 at 3 25 24 pm" src="https://user-images.githubusercontent.com/3435314/33311884-684f1aa2-d450-11e7-82d5-4e46bcc65a4b.png">

**Comment by whitedogg13** [comment]
Hi, I still cannot reproduce this error. Can you check which XCode version you currently use? NFC related functionality only available for XCode 9.

**Comment by milon87** [comment]
OS:  Sierra 10.12.6
XCode Version: 8.3.1 (8E1000a) 
ok in that case I will update to 9 and i will let you know

**Comment by whitedogg13** [comment]
Hi @milon87 any update for this one? I think the XCode 9 is definitely required for NFC development. Hope your upgrading process goes smoothly~

**Comment by milon87** [comment]
This happens because of Xcode version. 
required version 9
