### ISSUE TITLE
Reading NFC Tag types : “android.nfc.tech.NfcV” and “android.nfc.tech.NdefFormatable”

### ISSUE THREAD

**Issue by askongs** [whitedogg13/react-native-nfc-manager#128]
I am trying to read from a Bloodsugar Meter using NFC, right now on an Android, haven't tried iOS yet (don't have a phone with NFC), using only the Example application.

I am receiving this tag:

{ "techTypes":["android.nfc.tech.NfcV","android.nfc.tech.NdefFormatable"], "id":"87C5280D002602E0"}
I can see that NfcV is covered in this library, but How do I read it as that type ??

I am following the example so I haven't set anything in my manifest or my build.gradle. I have linked it and it is working, but im missing the last part it seems.

By following the example it looks like i am supposed to use a method like this:

```
_parseText = (tag) => {
    try {
        if (Ndef.isType(tag.ndefMessage[0], Ndef.TNF_WELL_KNOWN, Ndef.RTD_TEXT)) {
            return Ndef.text.decodePayload(tag.ndefMessage[0].payload);
        }
    } catch (e) {
        console.log(e);
    }
    return null;
}
```
But my tag doesnt have a ndefMessage[0].

Any ideas ? :)

**Comment by whitedogg13** [comment]
Hi, @askongs from the `techTypes` returned we can see that your tag doesn't contain any Ndef data, which means you might need to use lower level API to access the tag, such as `transceive`. The `transceive` API for `NfcV` tech is supported by this library. 

However, you will need specific knowledge about the tag (something like the tag memory layout or data sheet from the manufacturer) , since `transceive` is a low-level API to deal with NFC tag's internal memory. 

BTW, iOS can only deal with Ndef level data, there's Apple's policy and no way to workaround that.

**Comment by askongs** [comment]
Thank you for the quick response.

I am still confused about the byte array I need to use as argument for the transceiver.

I Do know a Block number for the data I am trying to pull = 210+211. - Is that what I need to rewrite as byte-array somehow ?

```
        NfcManager.registerTagEvent(tag => console.log(tag))
        .then(() => NfcManager.requestTechnology(NfcTech.NfcV))
        .then(() => NfcManager.getTag())
        .then(tag => {
            console.log(JSON.stringify(tag));
        })

        var bytes = undefined //Byte Map pointer
        .then(() => NfcManager.transceiver(bytes))
```

**Comment by askongs** [comment]
When I test same device on a iPhone it does show a ndef message ? - isn't that weird ?

_{"ndefMessage":[{"tnf":1,"payload":[2,101,110,255,255,48,55,53,48,49,49,67,72,0,1,0,85,0,170,0,0,0,8,28,59,254,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19,16,46,61,0,1,1,144],"id":[],"type":[84]}]}_

**Comment by whitedogg13** [comment]
@askongs It is indeed weird... Per my understanding, once a tag tech is supported and contains NDEF data, it should be the same in both platforms. I just label the issue as help wanted, to see if someone can answer that!

**Comment by whitedogg13** [comment]
close inactive issue

**Comment by Amanda1995pig** [comment]
Hi askongs ，I have the same problem as you. If you solve it,can you give me an example of how to read and write "android.nfc.tech.NfcV” and “android.nfc.tech.NdefFormatable" tag ?   Thanks a lot

**Comment by narayanratawa-eaton** [comment]
@askongs will you have to read/write using nfcv ?
