### ISSUE TITLE
How to read/write multi block for mifare classic?

### ISSUE THREAD

**Issue by chiphan2008** [whitedogg13/react-native-nfc-manager#135]

**Comment by poison** [comment]
Hi @chiphan2008 ,

To read a full sector, you can use the `mifareClassicReadSector` function. But you can always read multiple bocks by doing subsequent calls to the `mifareClassicReadBlock` function.

There's a good example in `example/AndroidMifareClassic.js`.

Let me know if you need further assistance!

Best regards,
Nicolas

**Comment by chiphan2008** [comment]
Do you have code demo for this action? I try these function in example/AndroidMifareClassic.js, but not respone.

**Comment by whitedogg13** [comment]
close inactive issue
