### ISSUE TITLE
Refusing to install package with name "react-native-nfc-manager" under a package npm ERR! also called "react-native-nfc-manager". Did you name your project the same npm ERR! as the dependency you're installing?

### ISSUE THREAD

**Issue by MssMaster** [whitedogg13/react-native-nfc-manager#136]
Getting above error while installing 'react-native-nfc-manager' inside example project.Please let me know what i am doing wrong.Also if i import android project in android studio and update it's gradle versions it does not show any configuration to run the code.Please let me know how i can fix it ?

**Comment by MssMaster** [comment]
Able to install the plugin by changing name of application to nfc-manager in package-json.js class. but still it does not display any run configuration in android studio.

**Comment by MssMaster** [comment]
Any One there ?

**Comment by whitedogg13** [comment]
@MssMaster I'm not sure I understand your issue. You should first create your own RN app, and npm install / react-native link this library. The example directory contains no full project.

**Comment by MssMaster** [comment]
Thanks for your reply,I am new to this, Now i am able to run the code and can see the Ui of screen but still start detection is not doing anything, i have nfc card with me i am taping it behind the device but the it is not getting detected by application.Even i tried to put alert inside _startDetection() method it's not getting called.

**Comment by MssMaster** [comment]
code of app.js class

**Comment by MssMaster** [comment]
yes, I am doing in same way.

**Comment by whitedogg13** [comment]
From the code you listed, the result will be passed into `_onTagDiscovered` callback~

**Comment by MssMaster** [comment]
yes, But I am not getting any value for the tag, seems it never goes into onTagDiscovered method.

**Comment by MssMaster** [comment]
can you please look into the above code and let me know if there is anything missing or wrong?

**Comment by whitedogg13** [comment]
close inactive issue
