### ISSUE TITLE
setTimeout function for transceive

### ISSUE THREAD

**Issue by hosseinpro** [whitedogg13/react-native-nfc-manager#137]
Hi 
I found that react-native-nfc-manager does not export Android NFC setTimeout function. I want to do a long processing task on card and react-native-nfc-manager returns "transceive fail".
When I remove long processing task from card, it works. Also I test my card with a USB reader with my laptop and there is no error.
According to this:
https://developer.android.com/reference/android/nfc/tech/NfcA.html#setTimeout(int)
And this:
https://stackoverflow.com/questions/6877650/changing-the-nfca-timeout-length-in-android
the default timeout is 300ms and we can extend it with setTimeout function.

**Comment by whitedogg13** [comment]
@hosseinpro thanks for the suggestion, we will add this API soon!

**Comment by whitedogg13** [comment]
Hi @hosseinpro we have added support for `setTimeout` in the latest 1.2.1, please have it a try!

**Comment by hosseinpro** [comment]
Thank you.

**Comment by MatteoAlberghini** [comment]
Hi, is this feature only for 1.x version? I don't see the `setTimout` function for 2.x

**Comment by arafat-al-mahmud** [comment]
Couldn't find setTimeout in 2.2.1

**Comment by suyog0391** [comment]
Missing this functionality in 2.2.1 latest version

**Comment by GitKokoszka** [comment]
Yes, it is missing for me too.

**Comment by whitedogg13** [comment]
Hi all, sorry for the late response, you guys are right, this one is indeed missing in type definition.

I have added it back in `2.3.1` and `3.1.1`, thanks!

**Comment by Ellathet** [comment]
How can use the timeout method? 
I try to use with await and try, how it is done in the doc:

```
  async function readNdef() {
    try {
      await NfcManager.requestTechnology(NfcTech.Ndef);
      const tag = await NfcManager.getTag();
      await NfcManager.setTimeout(60000 /* 1 minute in ms */);
    } catch (ex) {
      console.error('error')
    } finally {
      NfcManager.cancelTechnologyRequest();
    }
  }
  ```
