### ISSUE TITLE
NfcManager.getLaunchTagEvent doesn't get triggered when the app is running in background

### ISSUE THREAD

**Issue by sperera** [whitedogg13/react-native-nfc-manager#139]
Hi @whitedogg13,

NfcManager.getLaunchTagEvent is getting triggered as expected if the app is closed. But it is not getting triggered if the app is running in the background. Do you know a solution for this?

Thanks,
Sewwandi

**Comment by whitedogg13** [comment]
@sperera Hi, I wonder how do you trigger it in background? is via `HeadlessJS`?

**Comment by whitedogg13** [comment]
close inactive issue
