### ISSUE TITLE
ios session closed in iphone 7

### ISSUE THREAD

**Issue by adirzoari** [whitedogg13/react-native-nfc-manager#14]
Hello,
i'm trying to implement this plugin into my code and run nfc but I get these lines in console log
```
`registerTagEvent OK undefined
ios sessionClosed`

```
when I run the startDetection manually I get also the same issues..
part of my code
```
`import { calcSize } from '../../utillities/utilites';
const { height, width } = Dimensions.get('window');

import NfcManager, { NdefParser } from 'react-native-nfc-manager';

export default class NfcScan extends Component {
    constructor(props) {
        super(props);
        this.state = {
            supported: true,
            enabled: false,
            tag: {},
            spinValue: new Animated.Value(0),
            opacityAnimate: new Animated.Value(1),
            width: new Animated.Value(calcSize(197)),
            nfcDetection: false
        }
    }

    componentDidMount() {
        // StatusBar.setHidden(true);

        NfcManager.start({
            onSessionClosedIOS: () => {
                console.log('ios session closed');
            }
        }).then(result => {
                if(!result){
                    console.log("not nfc detected");
                }else
                    console.log('start OK', result);
            })
            .catch(error => {
                console.warn('start fail', error);
                this.setState({supported: false});
            })

        if (Platform.OS === 'android') {
            NfcManager.getLaunchTagEvent()
                .then(tag => {
                    console.log('launch tag', tag);
                    if (tag) {
                        console.log(tag);
                        this.setState({ tag });
                    }
                })
                .catch(err => {
                    console.log(err);
                })
            NfcManager.isEnabled()
                .then(enabled => {
                    console.log(enabled);
                    this.setState({ enabled });
                })
                .catch(err => {
                    console.log(err);
                })
        }
    }`
```

**Comment by whitedogg13** [comment]
Hi @adirzoari , thanks for adapting this library.

Regarding your questions:
1. Maybe you can try our sample to see whether it's working first. It's quite straightforward like this:
```javascript
// in your index.ios.js or index.android.js
import React, { Component } from 'react';
import {
  AppRegistry,
} from 'react-native';
import App from 'react-native-nfc-manager/example/App'

AppRegistry.registerComponent('NfcManagerDev', () => App);
```
2. If you still have problems integrating this library, you can post your full code (including the part calling `regsiterTagEvent`, which is missing in your code snippet above)

Thanks!

**Comment by adirzoari** [comment]
hey, 
I looked into the example I don't see any mention of registerTagEvent or any use of it.
I test your example and it still same issue. 
I tested it with some real phone of iphone 6,7 and galaxy. all of them has nfc.

it's all my code  ( I also don't have any registerTagEvent and also in your example into github I don't see any in the registerTagEvent
`import React, { Component } from 'react';
import {
    View,
    Text,
    Image,
    ImageBackground,
    Platform,
    TouchableOpacity,
    Linking,
    StatusBar,
    Animated,
    Easing,
    StyleSheet,
    Dimensions
} from 'react-native';
// import Svg,{
//     Circle,
// } from 'react-native-svg';


import { calcSize } from '../../utillities/utilites';
const { height, width } = Dimensions.get('window');

import NfcManager, { NdefParser } from 'react-native-nfc-manager';

export default class NfcScan extends Component {
    constructor(props) {
        super(props);
        this.state = {
            supported: true,
            enabled: false,
            tag: {},
            spinValue: new Animated.Value(0),
            opacityAnimate: new Animated.Value(1),
            width: new Animated.Value(calcSize(197)),
            nfcDetection: false
        }
    }

    componentDidMount() {
        // StatusBar.setHidden(true);

        NfcManager.start({
            onSessionClosedIOS: () => {
                console.log('ios session closed');
            }
        }).then(result => {
                if(!result){
                    console.log("not nfc detected");
                }else
                    console.log('start OK', result);
            })
            .catch(error => {
                console.warn('start failed', error);
                this.setState({supported: false});
            })

        if (Platform.OS === 'android') {
            NfcManager.getLaunchTagEvent()
                .then(tag => {
                    console.log('launch tag', tag);
                    if (tag) {
                        console.log(tag);
                        this.setState({ tag });
                    }
                })
                .catch(err => {
                    console.log(err);
                })
            NfcManager.isEnabled()
                .then(enabled => {
                    console.log(enabled);
                    this.setState({ enabled });
                })
                .catch(err => {
                    console.log(err);
                })
        }
    }
    _spin() {
        Animated.timing(this.state.spinValue, {
            toValue: 1,
            duration: 2000
        }).start(() => {
            this._spin();
        });
    }


    _scanAnimate() {
        Animated.sequence([
            Animated.timing(this.state.opacityAnimate, {
                toValue: 0,
                duration: 700
            }),
            Animated.timing(this.state.opacityAnimate, {
                toValue: 1,
                duration: 700
            })
        ]).start(() => {
            if (this.state.nfcDetection) {
                this._scanAnimate()
            } else {
                this.setState({ opacityAnimate: new Animated.Value(1) })
            }
        })

    }
    _onTagDiscovered = tag => {
        console.log("Discovered")
        
        console.log('Tag Discovered', tag);
        this.setState({ tag });
        let url = this._parseUri(tag);
        console.log(url);
        // if (url) {
        //     Linking.openURL(url)
        //         .catch(err => {
        //             console.warn(err);
        //         })
        // }
    }

    _startDetection = () => {
        console.log("_startDetection")
        NfcManager.registerTagEvent(this._onTagDiscovered)
            .then(result => {
                this.setState({ ...this.state, nfcDetection: false });
                console.log('registerTagEvent OK', result)
            })
            .catch(error => {
                console.warn('registerTagEvent fail', error)
            })
    }

    _stopDetection = () => {
        NfcManager.unregisterTagEvent()
            .then(result => {
                console.log('unregisterTagEvent OK', result)
            })
            .catch(error => {
                console.warn('unregisterTagEvent fail', error)
            })
    }

    _clearMessages = () => {
        this.setState({ tag: null });
    }

    _goToNfcSetting = () => {
        if (Platform.OS === 'android') {
            NfcManager.goToNfcSetting()
                .then(result => {
                    console.log('goToNfcSetting OK', result)
                })
                .catch(error => {
                    console.warn('goToNfcSetting fail', error)
                })
        }
    }

    _parseUri = (tag) => {
        console.log("_parseUri")
        
        let result = NdefParser.parseUri(tag.ndefMessage[0]),
            uri = result && result.uri;
        if (uri) {
            console.log('parseUri: ' + uri);
            return uri;
        }
        return null;
    }

    render() {
        let { supported, enabled, tag } = this.state;
        const { container, sloganContainer, bottomContainer, viewHeader, viewImageHeader, imgCircle, imgRectangle, imgScan, imgPhone, imgBub, nfcText, scanText, sloganText, bottomText } = styles;

        const spin = this.state.spinValue.interpolate({
            inputRange: [0, 1],
            outputRange: ['0deg', '360deg']
        })

        return (
            <View style={container}>
                <View style={viewHeader} />
                <View style={viewImageHeader}>
                    <Image
                        style={imgBub}
                        source={require('../../assets/images/Popups/popupScannedNewDrink/img_header_pop.png')} />
                </View>

                <Text style={nfcText}>
                    NFC Detected
                </Text>
              

    

                    <Text>{`Is NFC supported ? ${supported}`}</Text>
                <Text>{`Is NFC enabled (Android only)? ${enabled}`}</Text>

                <TouchableOpacity style={{ marginTop: 20 }} onPress={this._startDetection}>
                    <Text style={{ color: 'blue' }}>Start Tag Detection</Text>
                </TouchableOpacity>

                <TouchableOpacity style={{ marginTop: 20 }} onPress={this._stopDetection}>
                    <Text style={{ color: 'red' }}>Stop Tag Detection</Text>
                </TouchableOpacity>

                <TouchableOpacity style={{ marginTop: 20 }} onPress={this._clearMessages}>
                    <Text>Clear</Text>
                </TouchableOpacity>

                <TouchableOpacity style={{ marginTop: 20 }} onPress={this._goToNfcSetting}>
                    <Text >Go to NFC setting</Text>
                </TouchableOpacity>

                <Text style={{ marginTop: 20 }}>{`Current tag JSON: ${JSON.stringify(tag)}`}</Text> 
                <ImageBackground
                    style={imgCircle}
                    source={require('../../assets/images/NFC/img_circle.png')}>
                    <Animated.View style={{ opacity: this.state.opacityAnimate }}>
                        <TouchableOpacity
                            onPress={()=>this._startDetection()}>
                            <Text style={scanText}>
                                SCAN
                    </Text>
                        </TouchableOpacity>

                    </Animated.View>
                    {/* <Animated.Image
                        style={[imgScan,{opacity:this.state.width}]}
                        source={require('../../assets/images/NFC/img_scan.png')}
                    >
                    </Animated.Image> */}
                    <Image
                        style={[imgPhone]}
                        source={require('../../assets/images/NFC/img_phone.png')}
                    >
                    </Image>

                </ImageBackground>

                <View style={sloganContainer}>
                    <Text style={sloganText}>Place the beer glass behind the phone</Text>
                    <Text style={sloganText}>and press the Scan Button</Text>
                </View>

                <View style={bottomContainer}>
                    <Text style={bottomText}>How To Scan?</Text>

                    <TouchableOpacity
                        onPress={() => this.props.navigation.navigate('QrScan')}>
                        <Text style={bottomText}>Scan Using QR Code</Text>
                    </TouchableOpacity>
                </View>
            
            </View>
        )
    }
}


export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#3e445f',
        alignItems: 'center'
    },
    imgCircle: {
        // backgroundColor:'red',
        marginTop: calcSize(15),
        justifyContent: 'center',
        alignItems: 'center',
        width: calcSize(570),
        height: calcSize(570),

    },
    sloganContainer: {
        marginTop: calcSize(80),
        justifyContent: 'center',
        alignItems: 'center'
    },
    viewHeader: {
        backgroundColor: '#fed255',
        height: calcSize(116),
        width: width
    },
    imgBub: {
        resizeMode: 'contain',
        width: calcSize(195),
        height: calcSize(173),
    },
    viewImageHeader: {
        width: calcSize(160),
        height: calcSize(160),
        alignSelf: 'flex-end',
        marginTop: calcSize(-15),

    },
    imgScan: {
        width: calcSize(197),
        height: calcSize(266),

    },
    imgPhone: {
        width: calcSize(147),
        height: calcSize(266),

    },
    nfcText: {
        marginTop: calcSize(10),
        fontSize: calcSize(44),
        color: '#ffffff',
        fontFamily: 'Montserrat-Regular',
        marginBottom: calcSize(39)
    },
    scanText: {
        marginBottom: calcSize(42),
        fontSize: calcSize(83),
        color: '#ffffff',
        fontFamily: 'Montserrat-Regular',
        backgroundColor: 'transparent'
    },
    sloganText: {
        fontFamily: 'Montserrat-Regular',
        color: '#ffffff',
        fontSize: calcSize(28)
    },
    bottomContainer: {
        flex: 1,
        marginTop: calcSize(50),
        justifyContent: 'space-around',
        alignItems: 'center',

    },
    bottomText: {
        fontFamily: 'Montserrat-Regular',
        color: '#ffffff',
        fontSize: calcSize(28),
        fontWeight: '400'
    },


})`

**Comment by adirzoari** [comment]
my question is if I need to implement and follow the youtube tutorial?
If i make react native app, do i need to write all the codes the guy from youtube write into swift file in xcode?

**Comment by whitedogg13** [comment]
Hi, sorry for the late response.

You don't need to write any objective-c or swift code to use this library. However, you will need to do some project setup, please refer to `Prerequisites` section in following link:
* https://github.com/hansemannn/iOS11-NFC-Example

If the project is properly setup, you will see the NFC scanning you call `_startDetection`.

**Comment by whitedogg13** [comment]
As mentioned in #23 , iOS seems working now, so I close this for now.
