### ISSUE TITLE
Callback in NfcManager.registerTagEvent(Callback) doesn't trigger

### ISSUE THREAD

**Issue by pareshprajapati1990** [whitedogg13/react-native-nfc-manager#142]
In NfcManager.registerTagEvent(this.onTagDiscovered), onTagDiscovered never gets called.

**Comment by mantcz** [comment]
Check again if you have the library installed properly. I have just installed it and the callback works on both iOS and Android.

**Comment by pareshprajapati1990** [comment]
> Check again if you have the library installed properly. I have just installed it and the callback works on both iOS and Android.

Hi,
Thanks for answering to my query.

Can you please tell me which two devices did you use to test whether the callback is working properly or not?

**Comment by mantcz** [comment]
Hey @pareshprajapati1990 

I have used iPhone X with iOS 12 and Android device, Samsung 8 I believe.

**Comment by whitedogg13** [comment]
Hi all, since it's the basic functionality for this library, I believe it should work if the configuration is correct. I will close this issue for now, please re-open or fire another one if the issue remains!
