### ISSUE TITLE
How to parse this data with tnf=2? please help.

### ISSUE THREAD

**Issue by hhwill** [whitedogg13/react-native-nfc-manager#149]
ndefMessage: [
        {
          payload: [
            92,
            147,
            57,
            23,
            255,
            246,
            0,
            80,
            0,
            120,
            0,
            39,
            100,
            64,
            0,
            40
          ],
          type: [
            116,
            47,
            100,
            101,
            109,
            111,
            46,
            110,
            115,
            115,
            46,
            102,
            109,
            115,
            104
          ],
          id: [],
          tnf: 2
        },
        {
          payload: [54, 32, 0, 255, 243, 31, 67],
          type: [116, 47, 112],
          id: [],
          tnf: 2
        },
     ]

**Comment by marcorm** [comment]
@hhwill did you find any solution?
