### ISSUE TITLE
how to check if phone has nfc?

### ISSUE THREAD

**Issue by adirzoari** [whitedogg13/react-native-nfc-manager#15]
Hello,
is there any option to check with this plugin if iphone\android has nfc in the phone?

**Comment by whitedogg13** [comment]
Hi, thanks for the hint! We currently do lack this feature. 
I will try to implement this capability check and get back to you later.

**Comment by whitedogg13** [comment]
Hi @adirzoari I have implemented this in the latest version, now you can detect NFC support by seeing whether the promise returned by `NfcManager.start` call is resolved or rejected.
Thanks again for the suggestion!
