### ISSUE TITLE
Android: Getting error 'You can only issue one request at a time' while calling requestNdefWrite method

### ISSUE THREAD

**Issue by parvezq** [whitedogg13/react-native-nfc-manager#153]
Below given is react-native code for writing to the Mifare Ultralight NFC card:

`initiateWrite = async () => {
   const supported = await NfcManager.isSupported(NfcTech.MifareUltralight)
   if (supported) {
     console.warn('UltraLight Card is Supported')
     NfcManager.registerTagEvent((tag) => {
       console.warn(tag)
       NfcManager.requestTechnology(NfcTech.MifareUltralight).then(() => {

       })
       this.write("123456789");
     })

   }

 }
write =(text) => {
   var data = []        
         for (let i = 0; i < text.length && i < NfcManager.MIFARE_BLOCK_SIZE; i++) {
           data[i] = parseInt(text.charCodeAt(i));
         }
         console.warn(data)
var output = {}
         var i,j,temparray,chunk = 4, k = 0;
         for (i=0,j=data.length; i<j; i+=chunk) {
           temparray = data.slice(i,i+chunk);
           console.warn(temparray)
            NfcManager.requestNdefWrite(temparray, {format: true})
           .then(() => {
             console.warn('write done. ')
           })
           .catch((error) => console.warn(error))
           break
           k += 1
         }
 }`

**Comment by parvezq** [comment]
> Below given is react-native code for writing to the Mifare Ultralight NFC card:
> 
> `initiateWrite = async () => {
> const supported = await NfcManager.isSupported(NfcTech.MifareUltralight)
> if (supported) {
> console.warn('UltraLight Card is Supported')
> NfcManager.registerTagEvent((tag) => {
> console.warn(tag)
> NfcManager.requestTechnology(NfcTech.MifareUltralight).then(() => {
> 
> ```
>    })
>    this.write("123456789");
>  })
> ```
> }
> 
> }
> write =(text) => {
> var data = []
> for (let i = 0; i < text.length && i < NfcManager.MIFARE_BLOCK_SIZE; i++) {
> data[i] = parseInt(text.charCodeAt(i));
> }
> console.warn(data)
> var output = {}
> var i,j,temparray,chunk = 4, k = 0;
> for (i=0,j=data.length; i<j; i+=chunk) {
> temparray = data.slice(i,i+chunk);
> console.warn(temparray)
> NfcManager.requestNdefWrite(temparray, {format: true})
> .then(() => {
> console.warn('write done. ')
> })
> .catch((error) => console.warn(error))
> break
> k += 1
> }
> }`

This issue has been resolved as we found the problem in our code itself.

**Comment by jungRoit** [comment]
@parvezq can you share the fix that you used for this issue. I'm facing a similar issue

**Comment by visheshsprinzo** [comment]
@parvezq  yes same with me!
