### ISSUE TITLE
Is it possible to lock data in NFC?

### ISSUE THREAD

**Issue by marcelodelta** [whitedogg13/react-native-nfc-manager#154]
Hello.

Is it possible to lock data in NFC?

Blocking formatting and rewriting.

So it will not be rewritten in another application.

**Comment by whitedogg13** [comment]
Hi @marcelodelta sorry for the late response.

Yes, you can use `makeReadOnly` if you're targeting NDEF technology. To use a NFC technology, you can check `example/AndroidTechTestNdef.js`. The code probably looks like this:
```
NfcManager.registerTagEvent(tag => console.log(tag))
            .then(() => NfcManager.requestTechnology(NfcTech.Ndef))
            .then(NfcManager.getTag)
            .then(tag => {
                console.log(JSON.stringify(tag));
            })
            .then(NfcManager.makeReadOnly)
            ...
``` 

Hope that helps.
