### ISSUE TITLE
Is this works for external module?

### ISSUE THREAD

**Issue by muhammad-ihsan** [whitedogg13/react-native-nfc-manager#156]
Hi @whitedogg13 ,

is this working with external rfid reader? like USB RFID Smart Card Reader - EM4001
![Image of Yaktocat](https://ecs7.tokopedia.net/img/cache/700/product-1/2018/5/4/28967629/28967629_f07b915c-fcb9-4f53-bf90-cd79c6a97b00_350_350.jpg)

**Comment by whitedogg13** [comment]
Hi @muhammad-ihsan This library won't work with external NFC reader, it is used to bridge the Mobile OS NFC API (iOS/Android) to React Native.
