### ISSUE TITLE
Is it possible to have a custom mimeType for an NDEF_DISCOVERED?

### ISSUE THREAD

**Issue by miltonTouchdown** [whitedogg13/react-native-nfc-manager#158]
i want to have a custom mimeType for read a ndef, like to: 
mimeType="application/vnd.hello.sample.nfcmanager".

The project already have text/plain and uri. 

I need this for avoid conflicts with another applications on the devices.

Many thanks in advance for your answers

**Comment by whitedogg13** [comment]
Hi @miltonTouchdown sorry for the late response.

You can add following intent filter into your `AndroidManifest.xml` to achieve this:
```XML
<intent-filter>
    <action android:name="android.nfc.action.NDEF_DISCOVERED" />
    <category android:name="android.intent.category.DEFAULT" />
    <data android:mimeType="application/vnd.hello.sample.nfcmanager" />
</intent-filter>
```

Thanks!

**Comment by whitedogg13** [comment]
close inactive issue
