### ISSUE TITLE
Sample of formatting and writing NDEF to a Mifare Classic 1k chip

### ISSUE THREAD

**Issue by Thevertex** [whitedogg13/react-native-nfc-manager#161]
I was wondering if someone has a sample of formatting/writing NDEF to a Mifare Classic 1k using this library? I've tried several approaches but with no luck so far!

**Comment by whitedogg13** [comment]
@Thevertex sorry for the late response.

Great advice, I hope that as well. Since Mifare Classic uses proprietary mechanism, and I'm not an expert for this tag, I will label this issue as help-wanted to see if someone can help us.

Thanks!

**Comment by Thevertex** [comment]
No problems @whitedogg13 , I'm still working on the problem, if I do come up with a solution ill report it here
