### ISSUE TITLE
How to read Tag Id from multiple tag types

### ISSUE THREAD

**Issue by flowridr** [whitedogg13/react-native-nfc-manager#163]
I need to read id from tag which is either NfcA or NfcV. 

Is it possible to do this without calling NfcManager.requestTechnology multiple times?

**Comment by whitedogg13** [comment]
@flowridr yes, this is possible, you can call `registerTagEvent`, there's a `id` property inside the resolved value.

**Comment by ChristopheBelpaire** [comment]
Hello,
I have the same kind of problem. I would like to detect tag from type A B & V.
Is it possible to detect and request multiple technologies ?

**Comment by impl-kano** [comment]
@ChristopheBelpaire 
Hi, have you found any solution to detect type-B card? Thanks.
