### ISSUE TITLE
 NfcManager.isSupported() and all functions are not working in react native 0.59.8 version, while working in react native 0.57 version

### ISSUE THREAD

**Issue by KinjalDroid** [whitedogg13/react-native-nfc-manager#166]
NfcManager.isSupported(),
NFCManager.NfcManager.registerTagEvent(),
etc.. 
all functions are not working react native 0.59.8 version, while the same code is working fine in react native 0.57 version.

So what to do if I want to use NFC manager in react native 0.59.8 version ?
Please help me out.

**Comment by seonec** [comment]
i have the same problem. what is your solution?

RN: 0.60.3
react-native-nfc-manager: 2.0.0-beta.1
iOS: 12.3.1
