### ISSUE TITLE
On Start Tag Detection the app is crushing

### ISSUE THREAD

**Issue by sotir-ls** [whitedogg13/react-native-nfc-manager#169]
I am trying to implement a demo app with the bridge and examples.

When running on iOS 12, iphone Xr, the moment I click on _Start Tag Detection_ the app closes and it needs rebuilding.

There are no errors throws when running `react-native run-ios --device`, however from xCode there was a warning of missing _NFCManager.m_ file. I checked the library and it was successfully linked.

Clear cache, npm modules, re-installs, clear build folders. Tried all that it came to mind and I am not sure where the error might be. Has missing _NFCManager.m_ being reported before?

Stuck here.

Edit: It fails here:
```RCT_EXPORT_METHOD(registerTagEvent: (NSString *)alertMessage options:(NSDictionary *)options callback:(nonnull RCTResponseSenderBlock)callback)
{
    if (@available(iOS 11.0, *)) {
        if (session == nil) {
            BOOL invalidateAfterFirstRead = [[options objectForKey:@"invalidateAfterFirstRead"] boolValue];
            session = [[NFCNDEFReaderSession alloc] initWithDelegate:self queue:dispatch_get_main_queue() invalidateAfterFirstRead:invalidateAfterFirstRead];
            session.alertMessage = alertMessage;
            FAILS HERE =>>>[session beginSession];<<<=
        }
        callback(@[]);
    } else {
        callback(@[@"Not support in this device", [NSNull null]]);
    }
}```

**Comment by ignosis** [comment]
I'm having the same problem. In my case I'm trying with iPhone 8 and iOS 12 and the app crashes just at the same line commented by @Sotir-Akkroo. Do you have a fix or some workaround to solve it?
