### ISSUE TITLE
not work on react native version 0.60.0

### ISSUE THREAD

**Issue by gooking** [whitedogg13/react-native-nfc-manager#170]
not work on react native version 0.60.0

version 0.60.0 is up on ,We hope you can support it.

**Comment by whitedogg13** [comment]
@gooking Thanks for reporting, it should be related to the breaking change introduced by RN 0.60. I will check it out and fix it soon.

**Comment by fadyThePharaoh** [comment]
Can someone mention the latest stable version of react-native that is  compatible with react-native-nfc-manager ??
Thanks in advance.

**Comment by whitedogg13** [comment]
hi @fadyThePharaoh , it should work for all versions below RN 0.60 due to the breaking changes. I personally run several apps sing RN 0.56.0 with this lib and it works well.

**Comment by whitedogg13** [comment]
Hi @gooking @fadyThePharaoh , I have just updated a beta version targeting RN 60, currently versioned as beta to avoid affecting major RN 5x users. Please give it a try via:

`npm install react-native-nfc-manager@beta`

Related setup info is also updted in readme file, thanks!

**Comment by svvitale** [comment]
Tested on 0.60.3 and it works great!  Thanks, @whitedogg13 .
