### ISSUE TITLE
NativeNfcManager.js not included in the npm package

### ISSUE THREAD

**Issue by only1chi** [whitedogg13/react-native-nfc-manager#182]
When you download version 1.2.3 `NfcManager` imports `NativeNfcManager` from ./NativeNfcManager.js.
However when I install it, the folder inside `node_modules/react-native-nfc-manager `does not contain `NativeNfcManager.js`. 

This does not affect version 1.2.2 because it uses the NativeModules from react-native. 

This is android build.

**Comment by whitedogg13** [comment]
@only1chi Thanks for reporting! It's indeed a stupid bug in 1.2.3 release, and it's fixed in 1.2.4, please give it a try.

**Comment by only1chi** [comment]
It works now. Thanks!
