### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by roynes** [whitedogg13/react-native-nfc-manager#193]
**RN Version**: _0.60.5_
**This package version**: _1.2.4_

I've following manual linking since it won't work with auto linking.

but this problem still came out.

![Screen Shot 2019-09-05 at 6 00 11 PM](https://user-images.githubusercontent.com/12960236/64332374-0a706f80-d007-11e9-9d16-43c0bb5b2f59.png)

Is there anyway to fix this?

**Comment by roynes** [comment]
Additional errors in compiling.

![Screen Shot 2019-09-05 at 6 13 34 PM](https://user-images.githubusercontent.com/12960236/64333367-f463ae80-d008-11e9-9bf7-b26bde2a93b5.png)


![Screen Shot 2019-09-05 at 6 13 56 PM](https://user-images.githubusercontent.com/12960236/64333366-f3cb1800-d008-11e9-8078-78a44ee3c0a3.png)

**Comment by whitedogg13** [comment]
@roynes For RN60 + XCode 10, please use `2.0.0-beta.1`. Thanks!

**Comment by roynes** [comment]
@whitedogg13, tried it to build via xcode and it failed.

**Comment by whitedogg13** [comment]
@roynes Sorry for the late response. I have just test in on RN60.5, and it's OK. 

Here's my step for your reference:
```
react-native init NfcTestAppRn60 --version react-native@0.60.5
cd NfcTestAppRn60
npm install --save react-native-nfc-manager@2.0.0-beta.1
cd ios
pod install
```
Then open the `xcworkspace` file (not previous `xcodeproj`) in ios directory and it should work.

**Comment by whitedogg13** [comment]
Hi, for current dev, please follow this version guideline:

* XCode 11 beta + RN60: all 2.0.0-beta.X version should be fine
* XCode 10 + RN60: 2.0.0-beta.1
* XCode 10 + RN59 and below: 1.2.2

Thanks!

**Comment by roynes** [comment]
> @roynes Sorry for the late response. I have just test in on RN60.5, and it's OK.
> 
> Here's my step for your reference:
> 
> ```
> react-native init NfcTestAppRn60 --version react-native@0.60.5
> cd NfcTestAppRn60
> npm install --save react-native-nfc-manager@2.0.0-beta.1
> cd ios
> pod install
> ```
> 
> Then open the `xcworkspace` file (not previous `xcodeproj`) in ios directory and it should work.

Hi @whitedogg13 , by the word `open xcworkspace` does it pertain to open via `xcode`?

**Comment by roynes** [comment]
@whitedogg13,

I got it to work on the simulator now `iPhone X`

but what I got is this. 

`is NFC Supported? false`

![Screen Shot 2019-09-10 at 11 55 42 AM](https://user-images.githubusercontent.com/12960236/64583011-11f69680-d3c2-11e9-94ae-bf970e799db0.png)

**Comment by rahamin1** [comment]
I am having this problem in the following configurations:

- Xcode 11.3 + RN 59.9 + 1.2.2
- Xcode 11.3 + RN 59.9 + 2.0.0-beta.1

Any idea what to do?

**Comment by alexcastillo** [comment]
Same here. My configurations are:

 - Xcode 12.1 + RN 0.63.4 + react-native-nfc-manager 2.2.1

**Comment by alexcastillo** [comment]
A quick update:

I was able to fix the issue by adding iOS 14.3 [device support](https://github.com/filsv/iPhoneOSDeviceSupport) to my XCode since my iPhone is running 14.3.

**Comment by avivku90** [comment]
a quick question, can you write on an empty nfc tag after adding it? 

> A quick update:
> 
> I was able to fix the issue by adding iOS 14.3 [device support](https://github.com/filsv/iPhoneOSDeviceSupport) to my XCode since my iPhone is running 14.3.

**Comment by alexcastillo** [comment]
Hi @avivku90,

I haven't tried that, I'm mostly reading from tags. Maybe @whitedogg13 can help?

**Comment by whitedogg13** [comment]
@avivku90 it depends. 

If you're talking about writing NDEF, then you will need to first format the tag so you can write NDEF message into it. 

If you're using low-level NFC API, you should still be able to directly write into the tag's memory.

**Comment by whitedogg13** [comment]
Guys, I will close it for now, please feel free to reopen or drop a new one if issue persists.

**Comment by alexcastillo** [comment]
Thank you for your help, Richie!
