### ISSUE TITLE
EMV reader

### ISSUE THREAD

**Issue by jamie-kieran-martin** [whitedogg13/react-native-nfc-manager#195]
Hi I'm trying to implement an EMV reader into my app to accept payments. So far I'm able to read the tag, however having no luck from that. 

Is there any resources out there to help me in reading the data contained?

Best regards,
Jamie

**Comment by TheAussieStew** [comment]
@JamieKieranMartin Hi Jamie, did you get anywhere with this? Just wondering since I'm also trying to achieve the same thing.

**Comment by JamieKieranMartin** [comment]
@TheAussieStew I had no further luck unfortunately

**Comment by paranoia5** [comment]
@TheAussieStew @JamieKieranMartin have you guys found a solution for this issue?

**Comment by paranoia5** [comment]
@JamieKieranMartin I couldn't even read the tag on android? How were able to read the tag? I tried but I got no readings at all. :(((((

**Comment by jameslevine** [comment]
Anyone had any further luck on this? I'm trying to implement into a payment process too.

**Comment by jameslevine** [comment]
@whitedogg13 Is it possible to read EMV data from a card with this library? When I tried, I got tranceive fail console warning.

**Comment by manishbss-sdei** [comment]
Did any one find the solution for this issue ?

**Comment by eyodohan** [comment]
Did any one find the solution for this issue ?

**Comment by Ali-Aref** [comment]
Did any one find solutions for this issue?
