### ISSUE TITLE
`writeNdefMessage` is not working on iOS

### ISSUE THREAD

**Issue by deenMuhammad** [whitedogg13/react-native-nfc-manager#199]
I have been trying to test writeNdefMessage method on iOS.
packaget@beta
I am testing AppV2Ndef.js file with MifareUltralight NTAG 215 nfc tag.

Xcode: 11.0
React Native: 0.60.5
Device: iPhone 7 with iOS 13 installed. 

Following image is the log from Xcode:

<img width="557" alt="Screen Shot 2019-09-24 at 11 47 00 AM" src="https://user-images.githubusercontent.com/40787426/65477352-12625780-dec1-11e9-8376-8ff313aa698b.png">

Error in console is: "`ex Tag Not Found`"

Is there anything that i am missing?

**Comment by whitedogg13** [comment]
@deenMuhammad Sorry for the late response. Is the tag you used formatted?

**Comment by deenMuhammad** [comment]
should it be formatted or empty ?

**Comment by whitedogg13** [comment]
It should work on tags with existing NDEF message, but the tag needs to be formated, at least from the apple doc [link](https://developer.apple.com/documentation/corenfc/nfcndefstatus/nfcndefstatusnotsupported?language=objc). I havn't tried a unformatted tag yet.

**Comment by deenMuhammad** [comment]
i have tried many times in different tags. 
I also tried with iPhone8 and the function is writing 4 times out of 10 times in iPhone8+. 
To me it seems my iPhone 7 is not 100% compatible with the latest CoreNFC sw.
Or It seems to me that CoreNFC has some problem!
What do you think about that?
