### ISSUE TITLE
2.0.0 Beta on React Native version older than 0.60

### ISSUE THREAD

**Issue by joakimgrr** [whitedogg13/react-native-nfc-manager#202]
Hi,

I recently used the v1.2 to read and write data on an Android phone and i would need to extend this support on iOS, however in the installation instructions it seems that 2.0.0 beta can only be used on RN version 0.60 ? Is this correct or are the older versions supported as well?

Thank you for your hard work!

**Comment by joakimgrr** [comment]
At least my preliminary testing show that the 2.0.0-beta.4 is compatible with React Native 0.59.10

**Comment by whitedogg13** [comment]
@joakimgrr Great thanks for this info and sorry for the late response!
