### ISSUE TITLE
V2 beta 4 and onSessionClosedIOS

### ISSUE THREAD

**Issue by JimTeva** [whitedogg13/react-native-nfc-manager#204]
Hi everyone,
In V2.0.0-beta.4, on iOS the event onSessionClosedIOS doesn't seem to be recognized anymore.
`NfcManager.start({
      onSessionClosedIOS: () => {`
It is still an optional available parameter in the definition of .start() but it simply doesn't work for me.
Thanks in advance

**Comment by whitedogg13** [comment]
Hi, @JimTeva sorry for the late response. Please use `setEventListener(NfcEvents.SessionClosed, callback)` in V2 for this case, thanks!

**Comment by JimTeva** [comment]
Thanks @whitedogg13!

**Comment by JimTeva** [comment]
Just a quick update on this: it is somewhat slower to catch the event than before (in my case), is that the same for everyone?
