### ISSUE TITLE
tag content prefixed with 'en' 

### ISSUE THREAD

**Issue by jothikannan** [whitedogg13/react-native-nfc-manager#206]
I am using AndroidTechTestNdef.js from examples folder to read and write the tag using the react-native app. When I try to write a tag, the word 'en' prefixing all the time. It seems to be an issue for me. Can anyone help me to fix this?

I am checking it in Android version 9:

```
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-nfc-manager": "^2.0.0-beta.3"
```

Please refer attached images 
![IMG-20191011-WA0009](https://user-images.githubusercontent.com/4100047/66666175-b98b1100-ec6d-11e9-856d-97a13a1d98a0.jpg)
![IMG-20191011-WA0012](https://user-images.githubusercontent.com/4100047/66666178-babc3e00-ec6d-11e9-9247-81b1c54b8d06.jpg)

**Comment by whitedogg13** [comment]
Hi @jothikannan sorry for the late response, this issue has been fixed in `2.0.0-beta.4`, thanks!

**Comment by AlonsoBravo** [comment]
Same problem here, im using version 2.0.0

**Comment by crobinson42** [comment]
This is still an issue.
