### ISSUE TITLE
Problem with get uid mifare tag

### ISSUE THREAD

**Issue by CaldeDaniele** [whitedogg13/react-native-nfc-manager#211]
Hi,
I'm trying to get the uid of some nfc tag but I have some issue.
I follow this file 
> https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/AppV2Mifare.js

 and I'm in version

> "2.0.0-beta.4"

but at this line 47:
`let resp = await NfcManager.requestTechnology(tech, {
        alertMessage: 'Ready to do some custom Mifare cmd!'
      });
      console.warn(resp);`
nothing return and if I debug the NfcManager.js at line 173:
`NativeNfcManager.requestTechnology(tech, (err, result) => {
        if (err) {
          reject(err);
        } else {
          resolve(result);
        }
      })`

the err is "you need to call registerTagEvent first"

What can I do to proceed?

Thanks

**Comment by whitedogg13** [comment]
Hi @CaldeDaniele , sorry for the late response. It works well for me in RN60, could you try it with minimal setup (ex: empty project created by react-native cli) with latest `2.0.0` version?

**Comment by Serra19** [comment]
I'm on 2.0.1 (released today) and I'm having the same issue, but instead of "registerTagEvent", it says "registerTagEventEx".

It works fine on Android.

**Comment by CaldeDaniele** [comment]
Nothing, same issue in every situation.

**Comment by CaldeDaniele** [comment]
Ok! Solved!
the .entitlements need to be like this one:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>webcredentials:example.com</string>
	</array>
	<key>com.apple.developer.nfc.readersession.formats</key>
	<array>
    <string>TAG</string>
		<string>NDEF</string>
	</array>
</dict>
</plist>
```
