### ISSUE TITLE
How can i localize text 'Please tap NFC tags'?

### ISSUE THREAD

**Issue by jschenkDD** [whitedogg13/react-native-nfc-manager#212]
Hi,

reading nfc tags works fine. But even if i start reading a tag, popup contains the unlocalized text 'Please tap NFC tags'. Abort and everything else is localized. 

Is there a way to localize this text?
![Bildschirmfoto 2019-10-25 um 10 32 48](https://user-images.githubusercontent.com/21952805/67556268-247b2400-f713-11e9-9417-f982546693f8.png)

Thanks?

**Comment by whitedogg13** [comment]
Hi @jschenkDD , You can use `alertMessage` option to customize that string, like this:
```
await NfcManager.registerTagEvent({ alertMessage: '你好' });
```
