### ISSUE TITLE
NFCManager.registerTagEvent got 3 arguments expected 2 

### ISSUE THREAD

**Issue by gosuisez** [whitedogg13/react-native-nfc-manager#215]
I got the following error

![Screenshot_3](https://user-images.githubusercontent.com/31002587/67716055-b9ac4000-f9d3-11e9-8889-fce9410050d9.png)

**Comment by whitedogg13** [comment]
@gosuisez Sorry for the late resopse. It looks like a version mismatch between library and your client code. Please show me your code and library version for further info.

**Comment by bigescalade** [comment]
this is happening for me also on iOS 13, version 2.0.1.

`index 2 beyond bounds [0 .. 1]' was thrown while invoking registerTagEvent on target NfcManager with params (
    "",
        {
        invalidateAfterFirstRead = 0;
        isReaderModeEnabled = 0;
        readerModeFlags = 0;
    },
    1923
)`

**Comment by bigescalade** [comment]
This was an issue for my project using codepush, it was reverting the library back to an older version.

**Comment by anaraa3** [comment]
> This was an issue for my project using codepush, it was reverting the library back to an older version.

Hi @bigescalade,
My project using codepush, How to solve this problem when using codePush.

Hi @bigescalade,
My project using codepush, how to solve this problem when using codepush.

Please sharing your solution^

Thanks

**Comment by victorcorreae** [comment]
Hey @anaraa3 
I've had updated some packages including

> react-native-nfc-manager

So It was a version problem, so what worked for me was to clear all data, do a fresh install and rebuild.
