### ISSUE TITLE
NDEF Write functionality for 2.0.0-beta.1

### ISSUE THREAD

**Issue by joshdillner** [whitedogg13/react-native-nfc-manager#220]
Hi, I'm stuck using Xcode 10.1 for the time being, which means I have to use 2.0.0-beta.1 right?

Just wondering when/if you'll be implementing ndef write in 2.0.0-beta.1?

Cheers.

**Comment by whitedogg13** [comment]
@joshdillner sorry for the late response. 

To use NDEF writing, you have to upgrade to Xcode 11, otherwise there will be no latest Core NFC APIs. This is enforced by Apple, and we can do nothing to change that.

**Comment by joshdillner** [comment]
@whitedogg13 no worries, thanks for letting me know!
