### ISSUE TITLE
Iphone 7  IOS 13+ Isodep does not see ADPU card

### ISSUE THREAD

**Issue by orhanoksuzz** [whitedogg13/react-native-nfc-manager#221]
I use code example
https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/AppV2Apdu.js

It works fine on Android but does not see the card on the iphone side.

https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/AppV2Mifare.js

In this example, I can see the same card information, but I cannot send an ADPU command.

**Comment by thecalvinchan** [comment]
This fixed it for me https://github.com/whitedogg13/react-native-nfc-manager/issues/216#issuecomment-551168459

**Comment by orhanoksuzz** [comment]
> This fixed it for me [#216 (comment)](https://github.com/whitedogg13/react-native-nfc-manager/issues/216#issuecomment-551168459)


The solution failed for me.I can read tags with miframe, but when I select Isodep format to send adpu command, the card does not detect

**Comment by orhanoksuzz** [comment]
`  _test = async () => {
    try {
      let tech = NfcTech.IsoDep;
  
      let resp = await NfcManager.requestTechnology(tech, {
        alertMessage: 'Ready to send some APDU',
      });
     console.warn(resp)

      // the NFC uid can be found in tag.id
      let tag = await NfcManager.getTag();
      console.warn(tag)
   
      if (Platform.OS === 'ios') {
        resp = await NfcManager.sendCommandAPDUIOS(customapdu);
        } else {
        resp = await NfcManager.transceive(customApdu);
        }
      
     console.warn(resp)
      this._cleanUp();
    } catch (ex) {
       console.warn('ex',ex)
      this._cleanUp();
    }
  };`
Apple real device result:
error :" No tech matches"

**Comment by puneetmahali** [comment]
I am also facing the same issue on iPhone 7 real Device - "No tech matches" when i am trying to read the e-Passport chips. Has anyone solved this problem?

**Comment by whitedogg13** [comment]
Hi all, I can successfully send APDU to ePassport chip using iPhone 11 and this library. I will try to get a iPhone 7 and test it out.

For the testing, I simply use this [example](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/AppV2Apdu.js).

Some extra configs are required. You should declare the AID in your plist, to read ePassport:
```
	<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
	<array>
		<string>A0000002471001</string>
	</array>
```

You also need to add following into your entitlement:
```
<dict>
	<key>com.apple.developer.nfc.readersession.formats</key>
	<array>
		<string>NDEF</string>
		<string>TAG</string>
	</array>
</dict>
```

Also, please remember to enable NFC reading capability for your app in developer website: 
![image](https://user-images.githubusercontent.com/10307875/71583278-b145c200-2b48-11ea-80e4-4ae6964a65d0.png)

**Comment by orhanoksuzz** [comment]
> Hi all, I can successfully send APDU to ePassport chip using iPhone 11 and this library. I will try to get a iPhone 7 and test it out.
> 
> For the testing, I simply use this [example](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/AppV2Apdu.js).
> 
> Some extra configs are required. You should declare the AID in your plist, to read ePassport:
> 
> ```
> 	<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
> 	<array>
> 		<string>A0000002471001</string>
> 	</array>
> ```
> 
> You also need to add following into your entitlement:
> 
> ```
> <dict>
> 	<key>com.apple.developer.nfc.readersession.formats</key>
> 	<array>
> 		<string>NDEF</string>
> 		<string>TAG</string>
> 	</array>
> </dict>
> ```
> 
> Also, please remember to enable NFC reading capability for your app in developer website:
> ![image](https://user-images.githubusercontent.com/10307875/71583278-b145c200-2b48-11ea-80e4-4ae6964a65d0.png)

The cards I use do not have an ID. Guess the library has been updated. I haven't had a chance to try yet.I'll try it after Christmas.
