### ISSUE TITLE
Set Text in iOS NFC Reader - registerTagEvent - V2.x - Missing

### ISSUE THREAD

**Issue by mkharibalaji** [whitedogg13/react-native-nfc-manager#222]
Hi @whitedogg13,
            In the old version 1.x there are options to set the text for iOS in registerTagEvent but now in version 2.x i am not able to see one.

Can you help me on how to set the Text.

Thanks in advance

**Comment by whitedogg13** [comment]
@mkharibalaji this option is still valid, you can pass your custom message like this:
```javascript
registerTagEvent({ alertMessage: "My Message" })
```
