### ISSUE TITLE
getTag on ios is broken for new ISO7816 tags

### ISSUE THREAD

**Issue by thecalvinchan** [whitedogg13/react-native-nfc-manager#223]
https://github.com/whitedogg13/react-native-nfc-manager/blob/master/ios/NfcManager.m#L162

The line above attempts to `setObject` for application data, but in scanning new nfc chips, application data is potentially null, which causes an error.

A simple conditional could fix, but perhaps there is a more robust way of fixing

**Comment by thecalvinchan** [comment]
In fact, if we look at Apple's documentation, `applicationData` and `historicalBytes` can both be null

https://developer.apple.com/documentation/corenfc/nfciso7816tag

**Comment by whitedogg13** [comment]
@thecalvinchan good catch, this should be fixed in next release. Thanks!

**Comment by whitedogg13** [comment]
Fixed in latest v2.0.2, thanks!
