### ISSUE TITLE
Parsed url always resolves to play.google.com/store/apps/details?id=com.nfcdemo&feature=beam

### ISSUE THREAD

**Issue by ifeoluwak** [whitedogg13/react-native-nfc-manager#227]
Hi, I am using `v1.2.2` of this library, with react-native `0.61.5`. I am trying to get your [demo example](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/App.js) working but always get a link to my nonexistent app on playstore.

What can be the issue?

**Comment by whitedogg13** [comment]
@ifeoluwak sorry for the late response. Do you mean you just read the NDEF and get an incorrect result?

**Comment by ifeoluwak** [comment]
Yes whenever I read the tag I get that link as url
