### ISSUE TITLE
Can't read UID for MifareUltralight Tag

### ISSUE THREAD

**Issue by aminy** [whitedogg13/react-native-nfc-manager#228]
I'm using the example AppV2. I can read tag's payload, but I can't get tag's UID.
Do I need to make any changes to be able to read UID of a tag? 

React Native: 0.61.5
React Native NFC manager: 2.0.2
Xcode: 11.2.1

**Comment by whitedogg13** [comment]
@aminy in iOS, we can only get uid when requesting speicifc NFC technology like `Mifare` of `iso15693`. Since `AppV2` is used to scan general NDEF rather than specific type, there's no uid. You can try example `AppV2Mifare` to retrieve uid.
