### ISSUE TITLE
Share data between Android / IOS

### ISSUE THREAD

**Issue by rodgomesc** [whitedogg13/react-native-nfc-manager#229]
It's possible share data between Android and IOS using this library?

for example: 
- share link from Android to IOS
- share link from IOS to Android

And so on....

**Comment by whitedogg13** [comment]
Hi @rodgomesc Sorry for the late response. It's not possible to share data between iOS / Android using this library now. That's because this library only focus on "reader" mode of NFC, to communicate between devices, one of them should be a tag.

**Comment by ifeoluwak** [comment]
I would like to understand something, can we share data between Android to Android or iOS to iOS?

**Comment by rodgomesc** [comment]
@ifeoluwak Android <--> IOS using NFC

**Comment by whitedogg13** [comment]
@ifeoluwak Currently it's not possible to perform iOS to iOS communication. For Android to Android communication can be accomplished with 'Android Beam' feature, which is `NfcManager.setNdefPushMessage` API.

**Comment by amitbravo** [comment]
what are possibilities today ? can we share data between 2 devices ??

**Comment by whitedogg13** [comment]
Hi @amitbravo No, those APIs are deprecated by Google~
