### ISSUE TITLE
NTAG213, NTAG210u, or NTAG424?

### ISSUE THREAD

**Issue by bgold0** [whitedogg13/react-native-nfc-manager#231]
I'm buying a bunch of NFC Tags (500+) and want to make sure I get the right tags. Does anyone know what the appropriate tag I should get is?

**Comment by whitedogg13** [comment]
It depends on the operation you want to perform, and the data amount you want to use. If you simply need to write/read NDEF with small amount of data like url (ex: below 128 bytes), all tags should work.
