### ISSUE TITLE
Typescript declarations bugs (minor)

### ISSUE THREAD

**Issue by Frans-L** [whitedogg13/react-native-nfc-manager#232]
Hey!

Here are two minor typescript declarations errors that appeared:

1.) Currently, the typescript declaration says: _getNdefMessage(bytes: number[])_.  But _getNdefMessage_ should not take any parameter. 

2.) The function _setEventListener(name: NfcEvents, callback: OnNfcEvents)_  should also accept _null_ as a callback according to examples.

**Edit:** 

Made a fix. See the pull request: https://github.com/whitedogg13/react-native-nfc-manager/pull/233

**Comment by whitedogg13** [comment]
PR merged, thanks for the contribution!
