### ISSUE TITLE
Problem to start NFC Scanning in iPhone 7 IOS 13.3

### ISSUE THREAD

**Issue by MttNajafi** [whitedogg13/react-native-nfc-manager#234]
When I run this :
https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/AppV2.js
in iPhone 7 - IOS 13.3
it doesn't work but it works well in iPhone X- IOS 13.3

"react-native-nfc-manager": "^2.0.3",
"react": "16.9.0",
"react-native": "0.61.5",
Xcode : 11.3

![Screen Shot 2020-01-10 at 10 42 56](https://user-images.githubusercontent.com/36259426/72113970-42613800-3396-11ea-9327-541d8daf839d.png)
![Screen Shot 2020-01-10 at 10 43 22](https://user-images.githubusercontent.com/36259426/72113990-4d1bcd00-3396-11ea-9ca9-d09a024cad5d.png)

**Comment by yassine-be** [comment]
@MttNajafi did you find any solution to this.
i have the same problem, except it's the other way around.
It's working on iphone 7 not on iphone X
