### ISSUE TITLE
Mifare Plus X 2K

### ISSUE THREAD

**Issue by lordofflakes** [whitedogg13/react-native-nfc-manager#238]
Hello.
I'm trying to read Mifare Plus X 2K card on android, which is 2 kilobytes card. But when I try to read past 64th block I get and error:

`mifareClassicReadBlock fail: invalid block 64 (max 64)`

NfcManager.mifareClassicGetSectorCount() shows 16, but the card has 32 sectors.

Here is my code

```
      await NfcManager.registerTagEvent();

      let resp = await NfcManager.requestTechnology(NfcTech.MifareClassic, {
        alertMessage: 'Ready to write some NFC tags!'
      });

      const sCount = await NfcManager.mifareClassicGetSectorCount();
      const blockData = await NfcManager.mifareClassicReadBlock(65)
      console.log('scount', sCount, blockData)
```

**Comment by whitedogg13** [comment]
To be honest, I'm not familiar with MifareClassic... 
@poison Do you have any idea?
