### ISSUE TITLE
mifareClassicReadSector invalid data on certain devices

### ISSUE THREAD

**Issue by mhingston** [whitedogg13/react-native-nfc-manager#239]
Hi,

Using `NfcManager.mifareClassicReadSector` and inspecting the byte array returned for a given sector on a MifareClassic tag I'm finding that on a Huawei P8 Lite the byte array differs from what is being read from other devices as illustrated in this [diff](https://www.diffchecker.com/uAW0IQyt) (left being the expected data and right being what the P8 Lite is reading). As you can see the P8 Lite appears to be adding empty bytes to the byte array which is corrupting the data. I have tested reading the same MifareClassic tag using another NFC reader on the same P8 Lite and it reads the correct data so this doesn't appear to be a hardware issue, therefore I can only assume the issue is with this library?

Any advice would be appreciated.

Thanks

**Comment by whitedogg13** [comment]
To be honest, I'm not familar with MifareClassic. @poison Do you have any idea?
