### ISSUE TITLE
compileSdkVersion should bump to 26?

### ISSUE THREAD

**Issue by YKSing** [whitedogg13/react-native-nfc-manager#24]
According to the document from Google:
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

And also CRNA project eject to Expokit are also default to 26:
https://github.com/expo/expo/commit/e4b0ff087ffbf3c3092165bf8397ecdb820d2b82

**Comment by whitedogg13** [comment]
Hi, thanks for the suggestion! I will check if how this config affects the actual project and feedback later.

**Comment by 54vanya** [comment]
Hello, I can't compile release app without manually set compileSdkVersion 26, buildToolsVersion "26.0.2",  in library

**Comment by JoeDurand3** [comment]
Will this library not work with version 26+? Right now none of my registerTagEvent functions are firing, hopefully this is not why. (I'm using Version 27)

**Comment by whitedogg13** [comment]
Hi @JoeDurand3 @54vanya I plan to advance the compileSdkVersion and buildToolsVersion to 26 / 26.0.x in next release.

However, regarding your issues, I don't feel that they are related. I have just tested some combinations with current library:

1. SDK 26 + build tool 26.0.1/2 
2. SDK 27 + build tool 27.0.2

Both debug / release builds are tested, all of them run correctly.

If the issues persist, maybe you can update the build or runtime error messages so we can further investigate this.

**Comment by JoeDurand3** [comment]
Thanks @whitedogg13 . I'll open a separate issue for my problem.

**Comment by whitedogg13** [comment]
Hi all, I have advanced the SDK & build tool to 26 to latest release 0.5.4. Thanks you all!
