### ISSUE TITLE
Doesn´t work with clone card Arduino

### ISSUE THREAD

**Issue by vadermemo** [whitedogg13/react-native-nfc-manager#240]
Hi, this library is fantastic, but doesn´t work with clone cards for Arduino.

This are my specs in software

React native
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-nfc-manager": "^2.0.1"
  },

Xcode : Version 11.3 (11C29)

And this are my specs in hardware:

Device : Iphone 11 Pro Max, 
Version software 13.3

**Comment by whitedogg13** [comment]
Hi @vadermemo can you tell me:
1. which example do you use? 
2. the NFC technology for your tag (ex: Mifare, iso15693..etc)
