### ISSUE TITLE
React-Native Android: Getting error 'You can only issue one request at a time' after calling NfcManager.requestTechnology() on previous page. 

### ISSUE THREAD

**Issue by randacpan** [whitedogg13/react-native-nfc-manager#245]
Hello, i have implemented nfc manager. but when i tried it to read on another page, i have an error "You can only issue one request at a time".in the first page, i have call this method "NfcManager.cancelTechnologyRequest().catch(() => 0);", but still error on the next page. how to use this packages on two different pages in one project?

**Comment by randacpan** [comment]
i found the solution. sorry, thread closed.

**Comment by desteve** [comment]
Hi! Can you explain the solution? I'm facing a similar issue.

Thanks.
