### ISSUE TITLE
Isodep on ios errors with "No tech matches"

### ISSUE THREAD

**Issue by khpa** [whitedogg13/react-native-nfc-manager#248]
Hi, I'm trying to run the AppV2Apdu example on ios (13.3 iPhone 8) but get "No tech matches" when a device is placed on the phone. The device is an NXP (ISO14443-4), it works on android fine.

2020-01-29 13:55:38.219348+0000 ManageMii[10743:3198487] NFCTag didBecomeActive
2020-01-29 13:55:43.018625+0000 ManageMii[10743:3198487] NFCTag didDetectTags
2020-01-29 13:55:43.031 [info][tid:com.facebook.react.JavaScript] 'errors = ', 'No tech matches'

**Comment by whitedogg13** [comment]
hi @khpa , this means iOS doesn't consider the tag to have IsoDep tech. For iOS, it will automatically select AID for you, and you must write the AID down in your info.plist. However in Android, it simply gives you all capabilities to communicate with the NFC chip through `transceive` directly.

The ios part for AppV2Apdu.js expects a e-passport supported NFC chip, and you need to add following lines into you info.plist:
```
<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
<array>
    <string>A0000002471001</string>
</array>
```

**Comment by khpa** [comment]
hi @whitedogg13 sorry for the late reply, this worked, the AID is mandatory in info.plist, thanks again your help!
