### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by desteve** [whitedogg13/react-native-nfc-manager#250]
Hi everybody.

Just wanted to comment that most of the examples are not working, some of them can't even been built. Some work on Android but not in iOS. The version of the library to use with them is not clear. All these issues make the library hard to use and a time-consuming one, wasting hours for some easy test.
I think you should reconsider offering ready-to-go examples.

Regards.

**Comment by whitedogg13** [comment]
Hi @desteve , not sure what issues you encountered or what examples break through your comment. 

In NFC domain, most of the real use case involves specific NFC technology communication (Mifare, IsoDep or NfcV), and they’re generally domain specific and pretty complex, so we are not sure what kind of “ready-to-go” example to offer. Maybe you can tell us what example you expect, so we can make one for that.

**Comment by desteve** [comment]
Hi.

Sure, there are a lot of issues involving NFC technology, but I expect some simple clear information about library usage. In fact, I just expect something as simple as AppV2.js, but working on both platforms (iOS and Android).

Thanks.

**Comment by whitedogg13** [comment]
For me, the AppV2.js works for both platforms. 

Please notice that, in Android, there's no built-in NFC scan UI, so there won't be any visual cue after you tap the "Test" button, but once a tag is scanned, there will be a `console.warn` message.

Hope that helps.

**Comment by desteve** [comment]
Hi.
On Android it's working fine at first shot. Not in iOS, other apps are reading my tags perfectly but this is not happening with the library and this example. I'm driving nuts myself to get it working, changing library versions, detection flow, but I'm unable to put it to work.

Thanks.

**Comment by whitedogg13** [comment]
Hi @desteve for iOS, there're some extra configurations required. 
First, we need to enable the NFC capability in Apple developer site:
![image](https://user-images.githubusercontent.com/10307875/73804804-e906f000-47ff-11ea-83cd-6d43515dc2b9.png)

Also need to add the app's entitlement through Xcode:
![image](https://user-images.githubusercontent.com/10307875/73804959-5286fe80-4800-11ea-86bd-bff90e91a613.png)

Then we also need to add NFC privacy statement into Info.plist:
![image](https://user-images.githubusercontent.com/10307875/73804888-16539e00-4800-11ea-9b99-04058bb4c017.png)

I have put a [repo](https://github.com/whitedogg13/nfc-test-app) for your reference. Please feedback if there're any other issues.

**Comment by desteve** [comment]
Hi, thanks for your help.

I had all that configuration already done. In fact, iOS app starts to scan for NFC Tags (a system dialog appears reading to tap a tag), but no tag is detected, no matter which type. Same tags, are detected at first shot with different NFC reading apps available on AppStore.

Regards.

**Comment by whitedogg13** [comment]
Sorry to hear that, but that's all setup required at least in my case. I have tested on iPhone 8, XR, and 11.

Not sure what I can do to help, maybe you can try [this repo](https://github.com/whitedogg13/nfc-test-app) to see if it works...

**Comment by desteve** [comment]
Thanks for your help. I'll try the example you provide.
I'm closing the issue because I'm in some kind of dead-end which I have to solve by myself.

Thanks!

**Comment by desteve** [comment]
I get the example working finally! Still don't know what was the problem, but it's working.

Thanks for your help.
