### ISSUE TITLE
iOS 13.3 not working.

### ISSUE THREAD

**Issue by jbejas** [whitedogg13/react-native-nfc-manager#251]
Hello guys!

I've set up a React Native app to read NFC tags but it doesn't seem to work. The Reader dialog shows up, but nothing gets read.

Here is my code.

```
import React, { Component } from "react";
import { View, TouchableOpacity, Dimensions, Image, Platform } from 'react-native';
import NfcManager, {NfcEvents} from 'react-native-nfc-manager';
class RFIDREaderScreen extends Component {
  componentDidMount() {
    NfcManager.start();
    NfcManager.setEventListener(NfcEvents.DiscoverTag, tag => {
      console.warn('tag', tag);
      this.setState({ text: tag });
      NfcManager.setAlertMessageIOS('I got your tag!');
      NfcManager.unregisterTagEvent().catch(() => 0);
    });
  }

  componentWillUnmount() {
    NfcManager.setEventListener(NfcEvents.DiscoverTag, null);
    NfcManager.unregisterTagEvent().catch(() => 0);
  }
  _cancel = () => {
    NfcManager.unregisterTagEvent().catch(() => 0);
  }

  _test = async () => {
    try {
      await NfcManager.registerTagEvent();
    } catch (ex) {
      console.warn('ex', ex);
      NfcManager.unregisterTagEvent().catch(() => 0);
    }
  }
}
```

I'm using an iPhone 11 Pro with iOS 13.3

Here is my env info.

System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 49.49 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

I'm not sure what I'm missing here...

**Comment by whitedogg13** [comment]
Hi @jbejas ,

For iOS, there're some extra configurations required. 
First, we need to enable the NFC capability in Apple developer site:
![image](https://user-images.githubusercontent.com/10307875/73804804-e906f000-47ff-11ea-83cd-6d43515dc2b9.png)

Also need to add the app's entitlement through Xcode:
![image](https://user-images.githubusercontent.com/10307875/73804959-5286fe80-4800-11ea-86bd-bff90e91a613.png)

Then we also need to add NFC privacy statement into Info.plist:
![image](https://user-images.githubusercontent.com/10307875/73804888-16539e00-4800-11ea-9b99-04058bb4c017.png)

I have put a [repo](https://github.com/whitedogg13/nfc-test-app) for your reference. Please feedback if there're any other issues.

**Comment by yassine-be** [comment]
Hi @whitedogg13 , same as @jbejas , the v2 example not working on iphone7 and iphoneXS IOS 13.3.1
I have as you mentioned activated the NFC capability and added the permissions needed.
the app show the reading screen, but it's not detecting anything.

**Comment by whitedogg13** [comment]
Hi @yassine-be please try to use [this example](https://github.com/whitedogg13/nfc-test-app) to see if it works.
(in issue #250, some developer reports the issue been fixed by trying above example, although the root cause is not identified)

**Comment by yassine-be** [comment]
the example does not seem to work for me ( though working on android ).
can someone @whitedogg13 and @jbejas please confirm if scan is working on ios 13.3.1 for them.
i tried another app ("decode" from apple store) and it is not scanning either.

**Comment by whitedogg13** [comment]
Hi @yassine-be The example does work for me, on iOS 13.3 + iPhone 11. 

Can you check if your entitlement is correct like this?

![image](https://user-images.githubusercontent.com/10307875/74440720-7eae1980-4ea9-11ea-8181-1154bf0c2839.png)

(This file is automatically generated when we add our NFC capability in Xcode's `Signing & Capabilities` tab)

**Comment by yassine-be** [comment]
thanks @whitedogg13 for your help, the example is working for me now.
it turns out the tags i was testing with were not working on ios. I got some new ones and it's going smooth now.
i'm not sure as to why they worked only for android. I'll update my post if i find out.
