### ISSUE TITLE
TypeError undefined is not an object

### ISSUE THREAD

**Issue by Quintinator** [whitedogg13/react-native-nfc-manager#254]
So while developing my app I constantly run into the same error.
`TypeError: TypeError: Undefined is not an object (evaluating'_reactNativeNfcManager.NfcEvents.DiscoverTag')`

To start I have ejected my project using "Expo eject"
I have linked it
I start the app using "Npx react-native run-android" while my android phone is connected through USB.

The code is from the read exampe V2. 
` import React, { Component } from 'react';
import {     
    SafeAreaView,
    StyleSheet,
    View,
    Text,
    Alert,
    Platform,
    Image
 } from 'react-native';
import Dimensions from "Dimensions";
import { TextInput, TouchableOpacity } from 'react-native-gesture-handler';
import axios from "axios";
import NfcManager, {NfcEvents} from 'react-native-nfc-manager'

export default class NFCScreen extends React.Component {
    

    static navigationOptions = {
    };
    constructor(props) {
        super(props);
        this.state = {
            log: "Ready...",
            text: ""
        };
    }
    
    componentDidMount() {
        NfcManager.start();
        NfcManager.setEventListener(NfcEvents.DiscoverTag, tag => {
          console.warn('tag', tag);
          NfcManager.setAlertMessageIOS('I got your tag!');
          NfcManager.unregisterTagEvent().catch(() => 0);
        });
      }
    
      componentWillUnmount() {
        NfcManager.setEventListener(NfcEvents.DiscoverTag, null);
        NfcManager.unregisterTagEvent().catch(() => 0);
      }

    render(){
        const { navigate } = this.props.navigation;
        return (
            <View style={styles.container}>
                
                <View style={styles.knopView}>
                    <TextInput style={styles.handmatig}
                        returnKeyLabel='Done'
                        returnKeyType='done'
                        placeholder="Handmatig invoeren..."
                        onChangeText={(id) => this.setState({ id })}
                        value={this.state.id}

                    /*Code voor handmatige invoer, voor mensen zonder NFC-schip in hun telefoon*/
                    />

                    <TouchableOpacity style={styles.knop} onPress={this._handlePress.bind(this)}>
                        <Text style={styles.handmatigKnop}>OK</Text>
                    </TouchableOpacity>
                </View>

                <Image style={styles.nfcImage}
                    resizeMode="contain"
                    source={require("../../assets/images/nfcfc.png")}
                /*NFC logo*/
                />
                <Text style={styles.nfcText}>NFC</Text>
                <TouchableOpacity style={styles.scanKnop} onPress={this._test}/*Code voor de scan knop, bij ios moet deze ingedrukt worden*/>
                    <Text style={styles.scanText}>Scan NFC.</Text>
                </TouchableOpacity>
                <TouchableOpacity style={styles.scanKnop} onPress={this._cancel}>
                    <Text style={styles.scanText}>Cancel</Text>
                </TouchableOpacity>

            </View>
        );
        }

    async _handlePress(event) {
        const { navigate } = this.props.navigation;
        let manualId = this.state.id;
        try {
            
            // the API call
            let result = await axios.get(
                `https://api.concremote.com/Version/v1/factoryproductioncontrol/product?$filter=RFID%20eq%20'${manualId}'&$top=1&$expand=ProductType`);
            
            //shows what is in the array
            console.log(result.data.value)

            //Should technically show the Id that has been shown in the array.
            //console.log(result.data.value)
            const product = result.data.value[0];
            console.log('Product: ', product);
            console.log('Product id: ', product.Id);

            navigate("ProductScreen", {
                id: product.ProductType.Id,
                name: product.ProductType.Name + " " + product.Code
              });

        //Catch of the error
        } catch (err) {
            console.log(err);
            Alert.alert('Waarschuwing!', 'Het ingevoerde ID is onjuist.', [{text: 'Ok'}]);
         }
        // This shows which ID has been filled in.
        console.log(manualId);
    }

    _cancel = () => {
        NfcManager.unregisterTagEvent().catch(() => 0);
      }

    _test = async () => {
        try {
          await NfcManager.registerTagEvent();
        } catch (ex) {
          console.warn('ex', ex);
          NfcManager.unregisterTagEvent().catch(() => 0);
        }
      }

}
`

**Comment by Quintinator** [comment]
Tried some more but still haven't figured it out.

**Comment by whitedogg13** [comment]
Hi @Quintinator sorry for the late response.

I'm not using expo, but since this module contains native part, it will be easier to use `react-native-cli` to create project skeleton. 

For example:
```bash
npx react-native init NfcTestApp
cd NfcTestApp
npm i react-native-nfc-manager
```

Or, you can use this [repo](https://github.com/whitedogg13/nfc-test-app) as a starting point.

**Comment by Quintinator** [comment]
I'll try that. If that works I know it's due to issues with my project. Some other modules aren't working either

**Comment by Quintinator** [comment]
It works now. Project was configured through expo. Causing it not to work.
