### ISSUE TITLE
How to set initial IOS Alert Message when using `setEventListener`

### ISSUE THREAD

**Issue by bsbodden** [whitedogg13/react-native-nfc-manager#263]
You configure the initial message of the "Ready to Scan" dialog when using `requestTechnology`, like:

```
NfcManager.requestTechnology(tech, {
   alertMessage: "Read'em and weep"
});
```

Is there anything similar when using `setEventListener`? When reading a tag using code similar to https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/AppV2.js#L9 where can I set the `alertMessage` that shows on the "Ready to Scan" dialog?

```
 componentDidMount() {
    NfcManager.start();
    NfcManager.setEventListener(NfcEvents.DiscoverTag, tag => {
      console.warn('tag', tag);
      NfcManager.setAlertMessageIOS('I got your tag!');
      NfcManager.unregisterTagEvent().catch(() => 0);
    });
  }
```

Thanks!

**Comment by whitedogg13** [comment]
Hi @bsbodden , you can accomplish this by passing `options` into `registerTagEvent` API
```javascript
_test = async () => {
    try {
      await NfcManager.registerTagEvent({ alertMessage: 'My custom message' });
    } catch (ex) {
      console.warn('ex', ex);
      NfcManager.unregisterTagEvent().catch(() => 0);
    }
}
```
