### ISSUE TITLE
Read- and WriteMultipleBlocks are missing

### ISSUE THREAD

**Issue by Frans-L** [whitedogg13/react-native-nfc-manager#264]
Hey,

nfc15963 methods readMultipleBlocks and writeMultipleBlocks are missing for iOS. 

Have there been some technical difficulties with them or is just that no one has had time to do them? :)

I could help with them, but I just want make sure first that no one has started making them.

Regards,
Frans

**Comment by whitedogg13** [comment]
Hi @Frans-L I'm quite busy recently, and it's awesome that you can help, so please feel free to submit your PR!
