### ISSUE TITLE
iPhone 8 Plus not reading credit card

### ISSUE THREAD

**Issue by alucardeht** [whitedogg13/react-native-nfc-manager#265]
i used the example to try and nothing happens, i'm using iPhone 8 Plus and iOS 13.3.1

**Comment by whitedogg13** [comment]
Hi @alucardeht iOS cannot read credit card through NFC, since it won't accept payment related AID as mentioned in Core NFC doc [here](https://developer.apple.com/documentation/corenfc?language=objc).

**Comment by Noitidart** [comment]
@whitedogg13 it seems Apple changed the rules, they allow for adding a provision I noted here - https://github.com/revtel/react-native-nfc-manager/issues/173#issuecomment-1624326324
