### ISSUE TITLE
Android Mifare Example

### ISSUE THREAD

**Issue by Argecy** [whitedogg13/react-native-nfc-manager#266]
Hi.

I see a lot of IOS implementation examples but few to none examples for Android. I'm using Mifare DESFire cards which need to use the IsoDep tech and transcreive method. I've got experience with reading the cards on a native Android app however react native is new for me so I got no clue. 

Someone who can help me (or provide an example)?

**Comment by whitedogg13** [comment]
Hi @Argecy , you can use `IsoDep` tech to send raw `APDU` into your card directly, as in [this example](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/AppV2Apdu.js).

The main difference between iOS and Android is that the iOS requires you to explicitly specify your target `AID` in `info.plist` and it will perform the `select` AID for you, however Android wants you to `select` it manually.
