### ISSUE TITLE
ndefMessage payload differs on Android and iOS

### ISSUE THREAD

**Issue by chrisshiplet** [whitedogg13/react-native-nfc-manager#271]
My NFC tag returns an NDEF payload of `0x2ebc5363934d591e`. On iOS, this seems to be correctly represented as the payload `[2, 101, 110, 46, 188, 83, 99, 147, 77, 89, 30]`. On Android however, I get `[2, 101, 110, 46, -68, 83, 99, -109, 77, 89, 30]`. Note the two signed numbers.

Is there any way to decode this consistently on both platforms? It seems like iOS is the correct one here.

React Native version: 0.60.6
Library version: latest
iOS version: 13.3 (iPhone XS)
Android version: 9 (first gen Pixel)

**Comment by whitedogg13** [comment]
Hi @chrisshiplet thanks for reporting this issue, I will check it out  soon.

**Comment by whitedogg13** [comment]
Hi @chrisshiplet sorry for the late response! This issue has been fixed in the latest `v2.1.5`, thanks again for reporting!

**Comment by chrisshiplet** [comment]
Awesome, thanks for the quick turnaround!
