### ISSUE TITLE
[IOS]background NFC tag reading

### ISSUE THREAD

**Issue by danielprimat** [whitedogg13/react-native-nfc-manager#286]
There is any option to use react native for IOS, and launch the app by NfC event?

or that i have to use native code?

https://developer.apple.com/documentation/corenfc/adding_support_for_background_tag_reading
https://github.com/FabianGroeger96/NFC-Background-reading

Thanks for this amazing library

**Comment by csandman** [comment]
I am also in need of this feature, and I'm not sure how to implement it outside of this library

**Comment by fgrs** [comment]
anybody with the solution on iOS background tag scanning?

**Comment by goredefex** [comment]
First off, awesome library. Secondly...

I also need this feature... badly :(

**Comment by daheeahn** [comment]
I need this feature too.
