### ISSUE TITLE
Scan issues on iOS 13.3.1

### ISSUE THREAD

**Issue by Valandur** [whitedogg13/react-native-nfc-manager#289]
Following the example to read ndef tags I have added the following code
```typescript
await NfcManager.start();
NfcManager.setEventListener(NfcEvents.DiscoverTag, (e: TagEvent) => {
	const str = Buffer.from(e.ndefMessage[0].payload).toString('utf8');
	console.log(str);
});
await NfcManager.registerTagEvent();
```
during my component initialization.

This works perfectly on Android devices, but produces a warning in the logs on iOS:
`[CoreNFC] 00000002 80129180 -[NFCNDEFReaderSession _callbackDidBecomeActive]:228  Delegate does not implement -readerSessionDidBecomeActive: method`

The scanning system overlay for iOS shows up, but it never scans any tags.

If I copy and paste the lines [260-262](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/ios/NfcManager.m#L260-L263) of `ios/NfcManager.m` and rename the method to `readerSessionDidBecomeActive` then the warning in the logs goes away, and the scanning also works.

I'm not sure if I ran into an actual bug (possibly with older versions of iOS? Target deployment is set to iOS 9.0 for my project) or if I misconfigured something.

**Comment by gbettinazzi** [comment]
Same problem here, also targetting iOS 9.0

**Comment by gbettinazzi** [comment]
In my case it was my mistake because the tag I was using was empty

**Comment by Valandur** [comment]
Considering it works on Android I don't think an empty tag is the issue, at least for me.

**Comment by whitedogg13** [comment]
Hi @Valandur , I think @gbettinazzi is right. Tags contain no valid NDEF records will not be discovered by `registerTagEvent`, since we use `NFCNDEFReaderSession` under the hood for this case.

Can you try it again with tags contain valid NDEF message?

**Comment by Valandur** [comment]
Hi, sorry for the confusion, but I am actually using a tag with data. I was just thinking that the fact that it has data shouldn't matter for the firing of the event, but it possibly does?

The tags I'm reading do contain a valid NDEF message, and I also receive that data on Android. On iOS I only receive the data when adding the fix I posted above.

**Comment by Valandur** [comment]
I believe to have found the cause for this issue. I had to set `platform :ios, '11.0'` in my `Podfile`, not just in the main project. Now it seems to work, even without the additional line changes I mentioned.
