### ISSUE TITLE
Hello, do you have any sample code about NFCA reading? At present, in our project development, we use NFCA format storage devices. In demo, I don't see similar usage methods or know how to use the package. Can you help me? thank you

### ISSUE THREAD

**Issue by zouzheqiao** [whitedogg13/react-native-nfc-manager#292]
Hello, do you have any sample code about NFCA reading? At present, in our project development, we use NFCA format storage devices. In demo, I don't see similar usage methods or know how to use the package. Can you help me? thank you

**Comment by whitedogg13** [comment]
Hi @zouzheqiao sorry for the late response. Please use this [example](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/AppV2Mifare.js) as the example for NfcA.
