### ISSUE TITLE
Can I transfer data from iPhone to android phone by nfc

### ISSUE THREAD

**Issue by bigterboy** [whitedogg13/react-native-nfc-manager#297]
I have a app use nfc. And I want transfer a message from iPhone to android phone. Could this library support now. How about android phone to android phone. And I think this library has less document, so sometime I confused many thing!

**Comment by whitedogg13** [comment]
It's not possible for iPhone to iPhone and iPhone to Android. For Android to Android,  it can be done through `setNdefPushMessage`.
