### ISSUE TITLE
Find out if the android device "actually has" NFC

### ISSUE THREAD

**Issue by YKSing** [whitedogg13/react-native-nfc-manager#3]
I think the `isEnabled()` method should return null or throw exception 
__IF__ the android device actually DOES NOT have NFC

**Comment by whitedogg13** [comment]
Thanks for the feedback. It sounds reasonable and I will think about it!

**Comment by whitedogg13** [comment]
hi @YKSing thanks for the suggestion.

In the latest version, the `start` API can be used for this purpose, the returned promise will be `rejected` if platform doesn't support NFC.

Thanks.
