### ISSUE TITLE
Test suite failed to run. Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by DanielDanaee** [whitedogg13/react-native-nfc-manager#305]
RN 0.61.2
react-native-nfc-manager: ^2.1.4

![Screenshot 2020-06-23 at 16 44 53](https://user-images.githubusercontent.com/3917168/85418259-ddc71d80-b570-11ea-81b6-e1e3b712fdf7.png)

**Comment by whitedogg13** [comment]
Hi @alexcastillo 

I think you will need to mock the native module, since it doesn't exist in node environment. 

Something like this: https://github.com/naoufal/react-native-safari-view/issues/99

Thanks!

**Comment by alexcastillo** [comment]
Thanks for replying, @whitedogg13.

I should have clarified. I'm not trying to run tests, I'm just running the app.

I guess my issue has the same error. Please refer to #193 #148 #93

**Comment by alexcastillo** [comment]
Here's the output:

![image](https://user-images.githubusercontent.com/1181666/105257498-e955e380-5b55-11eb-8960-56e024ab5b4b.png)

**Comment by whitedogg13** [comment]
@alexcastillo @DanielDanaee For test fail, please try my suggestion above. I will close this issue for now, please refer to #193 for the same condition when actually running application.
