### ISSUE TITLE
Is there a way to disable the "ready to scan" popup on iOS? 

### ISSUE THREAD

**Issue by rahamin1** [whitedogg13/react-native-nfc-manager#309]
And be ready to scan without it, like android?

**Comment by marcosrdz** [comment]
Nope. Last time I checked this wasn't allowed under iOS.

**Comment by anaraa3** [comment]
@marcosrdz How to check this wasn't allowed under iOS?

**Comment by marcosrdz** [comment]
> @marcosrdz How to check this wasn't allowed under iOS?

Its part of the internal iOS code. Theres no way to start an NFC scan without it
