### ISSUE TITLE
Write NDEF record with low-level sendMifareCommandIOS and transceive

### ISSUE THREAD

**Issue by hannesschmidt** [whitedogg13/react-native-nfc-manager#314]
Hi,

I have successfully implemented the authentication of NTAG215 chips using the low-level sendMifareCommandIOS and transceiver API. To authenticate and write NDEF records in one session, I am relying on writing the NDEF records with the low-level APIs.

I am creating the NDEF record using
` 
const bytes = 
Ndef.encodeMessage([
    Ndef.wifiSimpleRecord({
      ssid: ssid,
      networkKey: key,
    }),
    Ndef.uriRecord(url),
  ]);
`
and trying to send it in pages of 4 bytes according to the specs of the NTAG215 inside a loop
`
await NfcManager.sendMifareCommandIOS([
      0xa2,
      pageAdress,
      ...slicedBytes,
    ]);
`
However, the NDEF records can not be detected as such, so it seems that I am missing some sort of extra format bytes. 
What else is happening to NDEF records using this library's writeNdef compared to e.g. sendMifareCommandIOS?

Best,
Hannes

**Comment by haitdm-viatick** [comment]
@hannesschmidt Could you please tell me the flow authentication of NTAG215. I need to authentication then read the data inside?
Thank you
