### ISSUE TITLE
Make App as NFC Card

### ISSUE THREAD

**Issue by Ov3rControl** [whitedogg13/react-native-nfc-manager#317]
Hello we are building smart doors that people can put their NFC cards on to unlock the door.
wondering if i can do the same thing but on mobile with this library? create an app that acs as a NFC Card (Not Reading or Writing)
The typical senario is i added some string on the mobile NFC when i put the app in front of the door. the door will scan the NFC data on the app and open the door.

How can i do something like that?

**Comment by StorkZ** [comment]
https://stackoverflow.com/questions/34607168/nfc-unavailable-when-camera-is-open

**Comment by jackgisel** [comment]
That would be really interesting. But, Apple doesn't give permission to do this. It's a closed API for their wallet app.

**Comment by svvitale** [comment]
This can be done on Android using card emulation, but as @jackgisel mentioned, not possible on iOS.

**Comment by appidea** [comment]
Hi, as @svvitale mentioned, it is possible to do using the HCE feature in Android. I just wrote the react-native extension "[react-native-hce](https://github.com/appidea/react-native-hce)", that supports the NFC tag emulation right away. Hope it will help.

**Comment by amitbravo** [comment]
@appidea so we can transmit from data from device A using react-native-hce and can receive data on B devices using react-native-nfc-manager , right ?

**Comment by amitbravo** [comment]
@Ov3rControl did you find any solution ?

**Comment by Ov3rControl** [comment]
@amitbravo no the project was cancelled so i didn't get the chance

**Comment by amitbravo** [comment]
can't simply 
react-native-nfc-manager work as sending data on one device and read on another device , same app .

**Comment by Malthehave** [comment]
@amitbravo did you ever figure out a solution for this? Thanks

**Comment by jeffinhk** [comment]
any updates on this one?
