### ISSUE TITLE
Doesn't seem to work with IOS 14 Beta

### ISSUE THREAD

**Issue by TylerNRobertson** [whitedogg13/react-native-nfc-manager#319]
Im not expecting this library to work with pre-release beta software but I'm putting this here because I have been experimenting & ran into this issue once the device is on IOS 14 Beta 4.

Could be an issue within the IOS beta or maybe they changed how interacting with the NFC native module works.

Inside the JS debugger you get: "No active session"

Inside XCode you receive: [30225:2089137] [CoreNFC] 00000002 8181d600 -[NFCTagReaderSession beginSessionWithConfig:]:315  error:Error Domain=NFCError Code=203 "System resource unavailable" UserInfo={NSLocalizedDescription=System resource unavailable}, errorCode: 0xcb

**Comment by TylerNRobertson** [comment]
@laurensk i just updated mine, mustve been an IOS specific issue.

**Comment by hunterbmt** [comment]
It's IOS specific issue, if I hard reset the iPhone, NFC Reader work for 1 time then not working anymore.

**Comment by laurensk** [comment]
Are you on Beta 5 or not?

**Comment by laurensk** [comment]
Summary: It seems like iOS 14 Beta 4 (and older) had issues with NFC scanning in general and it apparently has nothing to do with this package at all. Closing this issue now! Thanks for participating.

**Comment by jackgisel** [comment]
This can be closed.
