### ISSUE TITLE
Mifare iOS example crashes on iOS 13.6

### ISSUE THREAD

**Issue by RobertDoc** [whitedogg13/react-native-nfc-manager#322]
MifareV2 example in the repo does not seem to work on iOS 13.6. Crashes with very little error information given via XCode.

**Comment by jackgisel** [comment]
Could you give some more context? Maybe use a try/catch block and print the error.

**Comment by RobertDoc** [comment]
I sent screenshots to the primary contact on the repo. I'll see if I can post them here shortly.

**Comment by RobertDoc** [comment]
Tried again from scratch and it compiled and built this time - must have been me, apologies!
