### ISSUE TITLE
General Question : How to lock a tag ?

### ISSUE THREAD

**Issue by SlyBcDev** [whitedogg13/react-native-nfc-manager#323]
Hi,

 I use this library and it's work fine, really thanks for your job!

 So I saw that some app can definitivly  lock a tag to be writing. I would like to know if there is a possibility to do this with react-native-nfc-manager ?

Thanks
Sylvain

**Comment by jackgisel** [comment]
I think it is possible through the custom commands. I might work on that feature and create a PR at add it.

**Comment by traxx10** [comment]
> I think it is possible through the custom commands. I might work on that feature and create a PR at add it.

That would be great.
I would need this feature, please.
You can reach me at codetraxx10@gmail.com

**Comment by thatavivku90** [comment]
hey i would love to get more info about it too :) thanks!
avivku90@gmail.com

**Comment by mehdinasiripoor** [comment]
@jackgisel I would need this, thanks!
mehdi.nasiripoor@yahoo.com

**Comment by traxx10** [comment]
@jackgisel any updates on this?
