### ISSUE TITLE
How do I get the data of NFC ID card?

### ISSUE THREAD

**Issue by bymuh** [whitedogg13/react-native-nfc-manager#325]
in this [example](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/APIv2.md) return result:

```javascript
{
     id: "08F0F11E"
     techTypes: 
          0: "android.nfc.tech.IsoDep"
          1: "android.nfc.tech.NfcA"
}
```

**Comment by whitedogg13** [comment]
Hi @bymuh , you have to use NFC technology specific API to communicate with your tag:
* For Android, you should use `transceive`
* For iOS, it depends on your target NFC technology, for example:
    * `NfcA`: normally use `sendMifareCommandIOS`
    * `IsoDep`: use `sendCommandAPDUIOS`

However, it's beyond the scope of this library to provide actual payload for specific low-level operations.
