### ISSUE TITLE
Cannot listen Nfc state change on Android 

### ISSUE THREAD

**Issue by AdamChrist** [whitedogg13/react-native-nfc-manager#34]
HI,If the state(isEnabled) of the NFC changes, there is no way to monitor it.

**Comment by whitedogg13** [comment]
Hi, thanks for the feedback! I will try to implement this feature and keep you posted.

**Comment by whitedogg13** [comment]
Hi, this feature has been implemented in the latest version 0.3.0, thanks!

**Comment by AdamChrist** [comment]
@whitedogg13 thanks
