### ISSUE TITLE
IOS not writing not new nfc tag (empty) ios 14.1

### ISSUE THREAD

**Issue by avivku90** [whitedogg13/react-native-nfc-manager#340]
hey, i'm using
   "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-nfc-manager": "2.2.0",

when i try to write on an empty tag (new) using the example from here
https://github.com/whitedogg13/react-native-nfc-manager/blob/HEAD/example/AppV2Ndef.js

i get an error if i catch the writing event : 
NFCError:403

on android works fine and on ios works as long as the tag is not empty ( using third party apps)

please help! i'm working on app for clients and depending on you

**Comment by whitedogg13** [comment]
Please see instructions [here](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/FAQ.md#ios-cannot-write-ndef-into-nfc-tags).

I will close it for now, please feel free to reopen or fire another one if there’re still issues.

Thanks!
