### ISSUE TITLE
IOS 14 Not Writing

### ISSUE THREAD

**Issue by YusufBesim** [whitedogg13/react-native-nfc-manager#342]
Hello,

When we trying write ndef tag happens nothing.
Cannot continue after requestTechnology.

                  let resp = await NfcManager.requestTechnology(NfcTech.Ndef, {
                      alertMessage: 'Ready to write some NFC tags!'
                  });
                  console.warn(resp);
                  let ndef = await NfcManager.getNdefMessage();
                  console.warn(ndef);
                  let bytes = buildUrlPayload('https://test.com');
                  await NfcManager.writeNdefMessage(bytes);
                  console.warn('successfully write ndef');
                  await NfcManager.setAlertMessageIOS('I got your tag!');
                  this._cleanUp();

Thank you for help

**Comment by fgrs** [comment]
same issue on ios 14.4.2

**Comment by whitedogg13** [comment]
The same as #339, let's move our discussion there and close this one.
