### ISSUE TITLE
project with react-native v0.63.2 build with this lib failed with errors

### ISSUE THREAD

**Issue by reylen** [whitedogg13/react-native-nfc-manager#347]
ios project with react-native v0.63.2 build with this lib failed with errors

react dependency at new version had changed.
while change s.dependency to 'React-Core', build success.
may be  a change needed for this.

**Comment by CaptainBinouze** [comment]
I have a fail too! 
With "Component Exception - null is not an object (evaluating 'NativeNfcManager[name]')"
Is this the problem of dependency?
