### ISSUE TITLE
IOS fail to write on empty tag

### ISSUE THREAD

**Issue by avivku90** [whitedogg13/react-native-nfc-manager#351]
Has anyone manage to find a workaround or anything to deal with it?
I don't see any answer from the developers at the moment, anyone? any luck?

**Comment by whitedogg13** [comment]
Please see instructions [here](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/FAQ.md#ios-cannot-write-ndef-into-nfc-tags).

I will close it for now, please feel free to reopen or fire another one if there’re still issues.

Thanks!
