### ISSUE TITLE
Where should I get my tag data ?

### ISSUE THREAD

**Issue by Enzo-ltz** [whitedogg13/react-native-nfc-manager#356]
Hello ! 

I'm actually working on NFC with react-native and I'm now getting the following problem :

I used NFC Writter example to write an empty tag. This work since I get the correct result when I scan it with NFC Tools.
Here's what I write on my tag :
![image](https://user-images.githubusercontent.com/71329859/105468642-7b193a00-5c97-11eb-8677-b4fa34036e01.png)

However, with the NFC Reader example, I can't find the same data ! Here's what I can read : 
![image](https://user-images.githubusercontent.com/71329859/105468167-f8907a80-5c96-11eb-9e07-ce22ce23de66.png)

I would like to be able to find what I write ... Thank's for helping !

**Comment by whitedogg13** [comment]
Hi @Enzo-ltz your data is inside the `ndefMessage's payload` field. 

You will need to decode it to see the content, the code is something like this:
```javascript
import {Ndef} from 'react-native-nfc-manager';
...
Ndef.uri.decodePayload(ndefMessage[0].payload);
...
```

**Comment by TommysG** [comment]
> The above kind of works, but it should be in the documentation, clearly stated! Also, because we are using `uri`, it adds "https://www.en" in the front? How do we get just text?

You can use `Ndef.text.decodePayload` instead. I have this function in my code:

```ts
export const parseText = (tag: any) => {
  try {
    if (Ndef.isType(tag.ndefMessage[0], Ndef.TNF_WELL_KNOWN, Ndef.RTD_TEXT)) {
      return Ndef.text.decodePayload(tag.ndefMessage[0].payload);
    }
  } catch (e) {
    console.log(e);
  }
  return null;
};

```

and use it in my code like this:
```ts 
const tagData = parseText(tag) ?? tag?.id;
```

I hope that helps!!!
