### ISSUE TITLE
IOS 14+ doens't write on empty tag

### ISSUE THREAD

**Issue by avivku90** [whitedogg13/react-native-nfc-manager#363]
Writing on an empty tag doesn’t work, anyone figured it out it? some workaround maybe?

**Comment by whitedogg13** [comment]
Please see instructions [here](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/FAQ.md#ios-cannot-write-ndef-into-nfc-tags).

I will close it for now, please feel free to reopen or fire another one if there’re still issues.

Thanks!
