### ISSUE TITLE
[question] Is there any method to use NFC without calling NfcManager.registerTagEvent?

### ISSUE THREAD

**Issue by jopemachine** [whitedogg13/react-native-nfc-manager#365]
### Question

Hi, I'm wondering if I could implement using NFC feature without calling `NfcManager.registerTagEvent`.

Because I think it would be more convenient if the user could use the NFC function without pressing the button.

Is implementing this kind of feature impossible?

**Comment by whitedogg13** [comment]
Hi @jopemachine sure, you can simply put `registerTagEvent` Inside your `componentDidMount`, so the user don’t have to explicitly press any button.

I will close it for now, please feel free to re-open or fire another one if there’re other issues.
