### ISSUE TITLE
NFCError:200

### ISSUE THREAD

**Issue by YusufBesim** [whitedogg13/react-native-nfc-manager#367]
Hello,

When i try to write NFC i get "NFCError:200"

OS:  iOS 14.2
Device: Iphone 12 Pro

How can I fix that ? Thanks

**Comment by whitedogg13** [comment]
Hi, please check if your tag is properly formatted as NDEF. Please see instructions in [FAQ](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/FAQ.md#ios-cannot-write-ndef-into-nfc-tags).

I will close it for now, please feel free to reopen or fire another one if there’re still issues. Thanks!
