### ISSUE TITLE
write on empty tag ios

### ISSUE THREAD

**Issue by mehdinasiripoor** [whitedogg13/react-native-nfc-manager#369]
hello @whitedogg13,please save me.
ios writing not working on new tag(unformatted),when i formate the tag with another app and then try to write with your library, it is work but i need to do it in my own app, please help me.

**Comment by whitedogg13** [comment]
Please see instructions [here](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/FAQ.md#ios-cannot-write-ndef-into-nfc-tags). We have an example for naive NDEF formatting.

BTW, we have a slack channel here: https://join.slack.com/t/reactnativenf-ewh2625/shared_invite/zt-l2phclhi-AoYGQOOlCmvCSa3sBiA0IQ

You can join us for more detailed discussion.

I will close it for now, please feel free to reopen or fire another one if there’re still issues.

Thanks!
