### ISSUE TITLE
How to make read only tags on iOS?

### ISSUE THREAD

**Issue by nevens4fe** [whitedogg13/react-native-nfc-manager#370]
Hi,

As I can see in the code there is a method called makeReadOnlyAndroid(), is it possible to make tags readOnly on the iOS?

Thank you.
Regards

**Comment by whitedogg13** [comment]
Hi @nevens4fe thanks for spotting this! 

We have added this API into latest `v2.3.0` release, please give it a try. However please note that for iOS, it only works for NDEF level.

I will close this for now, please feel free to re-open or fire another one if there're still issues, thanks!
