### ISSUE TITLE
[v3] this.MIFARE_BLOCK_SIZE is not defined in MifareClassicHandlerAndroid

### ISSUE THREAD

**Issue by ale-rinaldi** [whitedogg13/react-native-nfc-manager#371]
Switching from v2 to v3, I started to get an error calling `NfcManager.mifareClassicHandlerAndroid.mifareClassicWriteBlock`:

```
Error: data should be a non-empty Array[undefined] of integers (0 - 255)]
```

From a look at the code it seems that MIFARE_BLOCK_SIZE is actually not defined anywhere.

Thank you

**Comment by whitedogg13** [comment]
Hi @ale-rinaldi thanks for reporting this! It's indeed an issue, and should be fixed in latest `v3.0.1`, please give it a try, thanks.

This issue is closed for now, please feel free to reopen it or fire another one if issue remains!
