### ISSUE TITLE
Read>Format>Write on one swipe.

### ISSUE THREAD

**Issue by Damian333** [whitedogg13/react-native-nfc-manager#372]
Is it possible to on one swipe read card > check if one of techTypes is android.nfc.tech.NdefFormatable and if is, format card > and then write card? 
Is it possible both on Android and IOS?

**Comment by whitedogg13** [comment]
@Damian333 Yes, It should be possible, but we will have to implement this for different NfcTechs.

For the most used NfcA (Mifare) tags, we have already implemented in [this project](https://github.com/revtel/react-native-nfc-rewriter), you can search for `NfcProxy.js` which has an `eraseNfcA` function does this.

Thanks!
