### ISSUE TITLE
Changelog [idea]

### ISSUE THREAD

**Issue by Frans-L** [whitedogg13/react-native-nfc-manager#374]
Hey!

Thanks for the new version! I really appreciate it.

One thing that would be cool to have is a changelog. It would make it easier to understand what's new and which changes have been the breaking ones. For example, currently, it's a bit hard to know how to migrate from v2 to v3.

Best regards,
Frans

**Comment by whitedogg13** [comment]
@Frans-L Thanks for your long-time contributions as well! 

It's a great idea, and I just added conventional changelog into release process, it should work in next release. I also generate changelog for the first time, please check it out [here](https://github.com/whitedogg13/react-native-nfc-manager/blob/main/CHANGELOG.md)

Sorry for the migration process, I haven't provided detail docs for this. However we have a slack channel to discuss, welcome to join us, it's easier to chat compare to github:
* Join here: https://join.slack.com/t/reactnativenf-ewh2625/shared_invite/zt-mxipzsua-Vns0lMlRUTHBJzOL1tLc4Q

Thanks!
