### ISSUE TITLE
NFCError 200 or NFCError 201

### ISSUE THREAD

**Issue by gospod1978** [whitedogg13/react-native-nfc-manager#376]
i just download this code and start to see how it's work.
I tried to read my Id card but always have error NFCError: 200.
I tried most of your code but the same NFCError:200
i using iPhone XR.
Can you help how to start read identity card Nationality.
I don't change nothing for your code.
made npm install
pod install
and whit xCode add the developer team.
No error when i build.
Some suggestion?
Thank you

**Comment by ibrahimdogruer** [comment]
@gospod1978  Any changes?
