### ISSUE TITLE
reset default app that opens via ndef

### ISSUE THREAD

**Issue by fgrs** [whitedogg13/react-native-nfc-manager#378]
I have this specific scenario... my tag contains ndef with a url then it gets scanned, a prompt shows up asking which app to open and there's a browser and my app to pick, the problem is sometimes user might accidentally choose a browser to open which is fine but is there a way so during next scan the prompt opens again so i can select my app instead of browser being opened by default?

**Comment by whitedogg13** [comment]
Hi @fgrs this is Activity Chooser is default behavior in Android platform, so we won't be able to change it.

However, in order to force your app to be launched by your NFC tag, you can refer to [this issue](https://github.com/whitedogg13/react-native-nfc-manager/issues/350)
