### ISSUE TITLE
Android, Native Popup opens automatically saying new tag scanned when tag is scanned. How Can we disable this?

### ISSUE THREAD

**Issue by jungRoit** [whitedogg13/react-native-nfc-manager#381]
Sometimes when scanning the NFC card a native popup saying New Tag Scanned appears and the functionality is not executed.

**Comment by whitedogg13** [comment]
Android will fire `NDEF_DISCOVERED` intent once a NFC tag contains valid URI, or MIME NDEF record, if no applications register for the intent, the system one will popup. 

To fix this, you can call `NfcManager.start`, this API will register for this intent in foreground, so the system one won't popup.

**Comment by whitedogg13** [comment]
I will close this for now, feel free to re-open or fire another one if there're still issues

**Comment by jungRoit** [comment]
Thank you so much.

**Comment by andreshsingh** [comment]
is it possible to disable the default scan ( "New tag scanned" ) before we call .start() ?

**Comment by Sewb21** [comment]
@whitedogg13 I am calling start in my application to register the intent to the foreground app but I am still getting the "New Tag Collected" system popup and when the NFC tag contains a URL it's navigating to the browser. Is there a way of stopping this?

**Comment by wordisthebird** [comment]
> @whitedogg13 I am calling start in my application to register the intent to the foreground app but I am still getting the "New Tag Collected" system popup and when the NFC tag contains a URL it's navigating to the browser. Is there a way of stopping this?

Any luck with this?

**Comment by Sewb21** [comment]
@wordisthebird I did resolve this a while ago, IIRC it was the way the link was being written to the tag but I can't fully remember and I don't have access to the code base to check
