### ISSUE TITLE
[IOS] NfcManager.requestTechnology is returning 'NFCError:204'

### ISSUE THREAD

**Issue by ibrahimdogruer** [whitedogg13/react-native-nfc-manager#382]
Hi. I study on project that i read a NFC token and write according to data in token.
I can read the token but i get an error while writing.
I guess i have to use requestTechnology method for can use writeNdefMessage method.
**On Android** works perfectly but on **IOS** requestTechnology is returning 'NFCError:204'.

Here is my code basically:
```javascript
await NfcManager.start();
console.log("<--- START --->");
await NfcManager.registerTagEvent().then(() => console.log("<--- Registered --->"));
await NfcManager.requestTechnology(NfcTech.Ndef) // or NfcTech.MifareIOS
      .then(res => console.log("Tech: ", res))
     .catch(err => console.log("Tech Err: ", err)) // <---- here
await NfcManager.writeNdefMessage(bytes)
      .then(() => {
          console.log("successful");
          _cleanUp();
      }).catch(err => {
          console.log("Write Error: ", err);
          _cleanUp();
      });
```
Console output: 
```
<--- START --->
<--- Registered --->
Tech Err:  NFCError:204
Write Error: No ndef available
```
I searched this error on web. 
It is meaning: ReaderSessionInvalidationErrorFirstNDEFTagRead - the initial ndef tag was invalid.
Why am i getting this error.

**Comment by whitedogg13** [comment]
@ibrahimdogruer Hi, this means the tag is not properly NDEF formatted. 

NDEF is a higher-level format on top of the raw NFC tag's internal memory structure. However, iOS requires you to first format the NFC tag into NDEF before you can write NDEF into it. On the other hand, Android isn't that strict about this.

You can check [FAQ](https://github.com/whitedogg13/react-native-nfc-manager/blob/main/FAQ.md#ios-cannot-write-ndef-into-nfc-tags) for some more explanation.
