### ISSUE TITLE
Missing constant in MifareUltralightHandlerAndroid class

### ISSUE THREAD

**Issue by arkabase** [whitedogg13/react-native-nfc-manager#387]
Version 3.2.1
In NfcTech/MifareUltralightHandlerAndroid.js, lines 12 and 15 :

`this.MIFARE_ULTRALIGHT_PAGE_SIZE` is undefined

this constant is not declared in the MifareUltralightHandlerAndroid class, and should be imported from NfcManager or NativeNfcManager

**Comment by whitedogg13** [comment]
Hi @arkabase, thanks for reporting this! I have fixed the issue and released v3.2.2
