### ISSUE TITLE
Don't have access to iOS error failures

### ISSUE THREAD

**Issue by ptfdln** [whitedogg13/react-native-nfc-manager#392]
## Description

iOS doesn't support passing the error from native to Javascript layer. I saw NfcErrorIOS were added recently, but I still think we don't have access to the error itself because it never gets bubbled up? I created a patch on a project, below for reference, and it works, feel free to use the same:

diff --git a/node_modules/react-native-nfc-manager/index.d.ts b/node_modules/react-native-nfc-manager/index.d.ts
index 267987c..3774417 100644
--- a/node_modules/react-native-nfc-manager/index.d.ts
+++ b/node_modules/react-native-nfc-manager/index.d.ts
@@ -170,7 +170,7 @@ declare module 'react-native-nfc-manager' {
   }
 
   type OnDiscoverTag = (evt: TagEvent) => void;
-  type OnSessionClosed = (evt: {}) => void;
+  type OnSessionClosed = (evt?: any) => void;
   type OnStateChanged = (evt: {state: string}) => void;
   type OnNfcEvents = OnDiscoverTag | OnSessionClosed | OnStateChanged;
 
diff --git a/node_modules/react-native-nfc-manager/ios/NfcManager.m b/node_modules/react-native-nfc-manager/ios/NfcManager.m
index a0c7657..73bcf87 100755
--- a/node_modules/react-native-nfc-manager/ios/NfcManager.m
+++ b/node_modules/react-native-nfc-manager/ios/NfcManager.m
@@ -195,7 +195,7 @@ - (void)readerSession:(NFCNDEFReaderSession *)session didInvalidateWithError:(NS
     NSLog(@"readerSession:didInvalidateWithError: (%@)", [error localizedDescription]);
     [self reset];
     [self sendEventWithName:@"NfcManagerSessionClosed"
-                       body:@{}];
+                       body:@{@"errorCode" : [NSNumber numberWithLong:[error code]]}];
 }
 
 - (void)tagReaderSession:(NFCTagReaderSession *)session didDetectTags:(NSArray<__kindof id<NFCTag>> *)tags
diff --git a/node_modules/react-native-nfc-manager/src/NfcManager.js b/node_modules/react-native-nfc-manager/src/NfcManager.js
index 5b0a9d2..218c445 100644
--- a/node_modules/react-native-nfc-manager/src/NfcManager.js
+++ b/node_modules/react-native-nfc-manager/src/NfcManager.js
@@ -136,10 +136,10 @@ class NfcManagerBase {
     }
   };
 
-  _onSessionClosedIOS = () => {
+  _onSessionClosedIOS = (evt) => {
     const callback = this._clientListeners[NfcEvents.SessionClosed];
     if (callback) {
-      callback();
+      callback(evt);
     }
   };
 

## Use Case

Differentiating from failures, example: User Cancel vs Timeout (200 vs. 201)

Thanks!

**Comment by whitedogg13** [comment]
@ptfdln great thanks for catching this! 

You're right since the previous modification focus on `requestTechnology` path, so the `registerTagEvent` path has been completely missed.

I have adapted your idea into the latest v3.5.0 release. 

The signature for `OnSessionClosed` now become `(error?: NfcError.NfcErrorBase) => void`, and we can distinguish the error through different types, like this:
```javascript
import NfcManager, {
  NfcError,
} from 'react-native-nfc-manager';

const handleException = (ex) => {
  if (ex instanceof NfcError.UserCancel) {
    // bypass
  } else if (ex instanceof NfcError.Timeout) {
    Alert.alert('NFC Session Timeout');
  } else {
    console.warn(ex);

    if (Platform.OS === 'ios') {
      NfcManager.invalidateSessionWithErrorIOS(`${ex}`);
    } else {
      Alert.alert('NFC Error', `${ex}`);
    }
  }
};
```
