### ISSUE TITLE
detecting start of the nfc scan

### ISSUE THREAD

**Issue by fgrs** [whitedogg13/react-native-nfc-manager#393]
is there a way to detect when scanning a tag has started so a "Loading" message can be shown before tag is successful scanned?

**Comment by whitedogg13** [comment]
@fgrs sorry for the late response.

For iOS, there's a built-in NFC scanning prompt pop-up, so the "loading" state should be pretty clear. For Android, there's no built-in UI so you will need to build it on your own.

You can use this [repo](https://github.com/revtel/react-native-nfc-rewriter) as an example. There's a [NfcPromptAndroid component](https://github.com/revtel/react-native-nfc-rewriter/blob/master/src/Components/NfcPromptAndroid.js), which is used to simulate the UI behavior on iOS.

I will close this for now. If there're still issues please feel free to re-open or fire another one!
