### ISSUE TITLE
Error: Redefinition of RCTMethodInfo after installing the plugin

### ISSUE THREAD

**Issue by adirzoari** [whitedogg13/react-native-nfc-manager#5]
Hello,
I opened a new react-native project (latest version V0.49) and after installing the plugin react-nfc-manager,
I'm trying to run on ios with XCode 9 (simulators I test:IPHONE 6,7,7s IOS 11) it failed with error:

![31434970-ade863a6-ae86-11e7-8e20-d6fec8d1df00](https://user-images.githubusercontent.com/20258998/31662648-f4a96a72-b347-11e7-9362-e95027c75b31.png)

when I run on android it works fine.

**Comment by whitedogg13** [comment]
Hi, @adirzoari thanks for interesting in this library!
I have already recognized the issue, and will quickly update new version once I verified the solution.

**Comment by whitedogg13** [comment]
Hi, this should be fixed by PR #4 
Thanks!
