### ISSUE TITLE
Unable To write Plain text

### ISSUE THREAD

**Issue by sourav-dev-meme** [whitedogg13/react-native-nfc-manager#51]
Need Help to write plain text. Is there any option where we can right plain text. Right now whatever we write is saved as URL.

Thanks in Advance !

**Comment by whitedogg13** [comment]
Hi, I will check it out soon when I'm available :)

**Comment by sourav-dev-meme** [comment]
Thanks for reverting back. 
Waiting for the solution :)

**Comment by whitedogg13** [comment]
Hi, I have just updated the `example/App.js` to include a RTD_TEXT example. Just like the url example, it allows you to write arbitrary text as RTD_TEXT record in the latest commit, please check it out!

Source is [here](https://github.com/whitedogg13/react-native-nfc-manager/blob/master/example/App.js), you can refer to the `_requestNdefWrite` function.

Thanks!

**Comment by whitedogg13** [comment]
Hi, @sourav-dev-meme how's going? Are there still any issues?

**Comment by whitedogg13** [comment]
Close due to no further activity
