### ISSUE TITLE
 Package community.revteltech.nfc does not exist

### ISSUE THREAD

**Issue by ragasjohn** [whitedogg13/react-native-nfc-manager#52]
Hello, 

I am getting the following error after react-native run-android 

package community.revteltech.nfc does not exist
import community.revteltech.nfc.NfcManagerPackage;

**Comment by whitedogg13** [comment]
Hi, do you run `react-native link react-native-nfc-manager`? Looks like the native module is not properly linked.

BTW, if you're using `expo`, you will need to eject first.

Thanks!

**Comment by whitedogg13** [comment]
Close due to no further activity
