### ISSUE TITLE
TypeError undefined is not an object

### ISSUE THREAD

**Issue by vivikenen** [whitedogg13/react-native-nfc-manager#56]
Hi there, 
I was trying to implement this package on my react-native project, but when I try to reference the functions from the `NFCManager` from `react-native-nfc-manager`, all the functions `catch` error instead of going to `.then`.

`"react-native": "^0.47.0",`:
`"react": "^16.0.0-alpha.12",`

Android Device:
`Android Version: 7.1.1`

I did the following setting steps: 
`npm install -s react-native-nfc-manager`
`react-native link react-native-nfc-manager`

I try to print its error message, it says:
you could ignore the string `start`, the `start` is hard code. 😂 
![screenshot_2018-05-03-10-28-24](https://user-images.githubusercontent.com/11569400/39555888-c61df0a6-4ebf-11e8-9942-8cb4f4a5eef0.png)

Is there any steps that I missing? Thx~

**Comment by vivikenen** [comment]
When I try to link the package, the response looks different from another package
![wechatimg75](https://user-images.githubusercontent.com/11569400/39557071-542e165c-4ec8-11e8-9638-241ca3cc9f2d.jpeg)

**Comment by vivikenen** [comment]
@whitedogg13  Thx for replying~
I'm not using the expo, should be `react-native-cli`

**Comment by whitedogg13** [comment]
Hi, if you're trying manually import, you can refer to #33 

Thanks!

**Comment by vivikenen** [comment]
@whitedogg13  thx for your replying, the package has been link successfully now~
