### ISSUE TITLE
Getting 'device does not support nfc!' on an NFC compatible Android

### ISSUE THREAD

**Issue by arapocket** [whitedogg13/react-native-nfc-manager#59]
I'm using an Axon 7 Mini and I have NFC enabled in the settings.

Anyone else have this issue with the same device or a different one?

**Comment by arapocket** [comment]
I see a similar issue in [https://github.com/whitedogg13/react-native-nfc-manager/issues/33](https://github.com/whitedogg13/react-native-nfc-manager/issues/33)

**Comment by JoeDurand3** [comment]
Can you show what your MainApplication.java file looks like? I'm having the exact same issue, yet I beleive am linked correctly.
