### ISSUE TITLE
getNdefMessage is not work

### ISSUE THREAD

**Issue by jiwenjiang** [whitedogg13/react-native-nfc-manager#61]
hi,
I copy the codes of `AndroidTechTestNdef.js` to my propject. but there are something wrong .

first time i detect the card , i get a warning of 'fail to connect tag'

second time i get the  tag, its a object combine with id&&techType, but the getNdefMessage is also cant work.

Do I need to do some configuration in AndroidManifest.xml?

----------------------
"react-native": "0.55.4",
"react-native-nfc-manager": "0.5.0"
----------------------
thx

**Comment by whitedogg13** [comment]
Hi, sorry for the late response.

In this case, `fail to connect tag` might happen if your tag isn't Ndef compatible.

You can verify this by running `example/App.js` and simply tap the tag to see the `techType` array contains **android.nfc.tech.Ndef**.

Thanks!

**Comment by whitedogg13** [comment]
Close due to no further activity.
