### ISSUE TITLE
iOS saying NFC not supported

### ISSUE THREAD

**Issue by rgpass** [whitedogg13/react-native-nfc-manager#63]
## Issue

I have installed react-native-nfc-manager in my app and it works perfectly on Android but not on my iPhone 8.

Note: This is my first time using a `react-native link`'ed module.

## Code

```js
NfcManager.start({
  onSessionClosedIOS: () => {
    console.log('ios session closed')
  },
})
  .then(result => {
    console.warn('start OK', result)
  })
  .catch(error => {
    console.warn('device does not support nfc!')
  })

NfcManager.registerTagEvent(
  tag => {
    // console.warn('Tag Discovered', tag)
    // console.warn(JSON.stringify(tag, null, 2))
    // console.warn(tag.ndefMessage[0])
    console.warn(NdefParser.parseText(tag.ndefMessage[0]))
  },
  'Hold your device over the tag',
  true
)
```

## Current Behavior

*Android*

Warning of `start OK undefined`. When scanning an NDEF NFC card, I get the message that's encoded. In other words, the line of `console.warn(NdefParser.parseText(tag.ndefMessage[0]))` prints out the message I want.

*iOS*

Warning of `device does not support nfc!`. Another warning of

```
Sending `NfcManagerSessionClosed` with no listeners registered.
```

## Expected Behavior

Both to behavior like Android's current behavior listed above.

## Theories

* I didn't do the Podfile installation process because I thought the `react-native link` would do it under-the-hood
* I didn't do anything regarding NFC permissions with Xcode

**Comment by whitedogg13** [comment]
Hi, thanks for trying this library!

You will need to do some configuration for iOS, here you can find the details:
* https://github.com/hansemannn/iOS11-NFC-Example

**Comment by rgpass** [comment]
That worked. Thanks! Good job on the library -- it works wonderfully!

**Comment by whitedogg13** [comment]
I'm glad to help!
