### ISSUE TITLE
Re-prompting on iOS

### ISSUE THREAD

**Issue by rgpass** [whitedogg13/react-native-nfc-manager#64]
## Issue

I have the library installed and working on iOS. I have set a button to run `NfcManager.start()` which opens the iOS prompt to scan the device. When pressing the button the first time, the prompt shows up. When pressing cancel then the button a second time, nothing shows up.

## Code

```js
const handleOnPress = () => {
  console.warn('pressed')

  NfcManager.start()

  const { sendReading } = this.props
  NfcManager.registerTagEvent(
    tag => {
      const reading = NdefParser.parseText(tag.ndefMessage[0])
      sendReading(reading)
    },
    'Hold your device over the tag',
    true
  )
}
```

## Current Behavior

*iOS*

Prompt not showing up a second time when the button is tapped.

*Android*

Works perfectly. This is because it's an "always-on" state, rather than requiring a button to toggle a prompt.

## Expected Behavior

After tapping the button a second time, I expected the prompt to show up again.

## Theories

* Need to call `stop()` when it is closed and restart it. This didn't work. See code below.

```js
const handleOnPress = () => {
  console.warn('pressed')

  NfcManager.start({
    onSessionClosedIOS: () => {
      NfcManager.stop().then(() => handleOnPress())
    },
  })

  const { sendReading } = this.props
  NfcManager.registerTagEvent(
    tag => {
      const reading = NdefParser.parseText(tag.ndefMessage[0])
      sendReading(reading)
    },
    'Hold your device over the tag',
    true
  )
}
```

* Need an API to refresh `NFCNDEFReaderSession`
* I've tried re-rendering this component, even rendering another one then coming back, and it is stuck
* I randomly got a warning of ``Sending `NfcMangerSessionClosed` with no listeners registered.`` -- it may be related to that?

**Comment by whitedogg13** [comment]
Hi, in above code try to use `unregisterTagEvent` rather than `stop` (in `onSessionClosedIOS`) should work!

**Comment by rgpass** [comment]
Got it working! It may be good to put this in the `README.md`. My example that I got working:

```js
constructor(props) {
  super(props)

  this.handleOnPress = this.handleOnPress.bind(this)
}

componentWillMount() {
  this.handleOnPress()
}

handleOnPress() {
  NfcManager.start({
    onSessionClosedIOS: () => {
      NfcManager.unregisterTagEvent()
        // Throws error but still works
        // This silences the error
        .catch(() => {})
    },
  })

  const { handleSendReading } = this.props
  NfcManager.registerTagEvent(
    tag => {
      const reading = NdefParser.parseText(tag.ndefMessage[0])
      handleSendReading(reading)
    },
    'Hold your device over the tag',
    true
  )
}
```

Thanks again for the help.

**Comment by rahamin1** [comment]
@rgpass Long time passed, I hope that you remember...

I assume that after calling NfcManager.unregisterTagEvent() in onSessionClosedIOS, you also call NfcManager.registerTagEvent, right?

**Comment by rgpass** [comment]
Sorry dude, I do not remember. Best of luck, though!
