### ISSUE TITLE
API to get UID

### ISSUE THREAD

**Issue by rgpass** [whitedogg13/react-native-nfc-manager#65]
## Issue

I can't access the meta info for the tag, such as UID.

## Code

```js
NfcManager.registerTagEvent(
  tag => {
    console.warn(tag)
  },
  'Hold your device over the tag',
  true
)
```

## Current Behavior

*iOS & Android*

The `tag` returned does not include any information about the id. `tag.ndefMessage[0].id` exists but is an empty array.

## Expected Behavior

Either `tag.ndefMessage[0].id` returns the UID or `tag.uid` returns the UID.

## Theories

None

**Comment by whitedogg13** [comment]
Hi, sorry for the late response!

For iOS, there's no UID available.
For Android, it should be in `tag.id` rather than `tag.ndefMessage[0].id`. The former one is uid and the later one is corresponding to the Ndef Record id which is rarely used.

Thanks!

**Comment by rgpass** [comment]
Gotcha. Is it not possible on iOS at all or just with this library?

**Comment by rgpass** [comment]
I see. Hopefully this changes in the future!

**Comment by cavasinf** [comment]
> [!NOTE]  
> In order not to "scare" new developers, I'll write it there.

Using `NDEF` technology you can get the UID on **iOS AND Android** like this:
```js
try {
  await NfcManager.requestTechnology([NfcTech.Ndef])
  const tag = await NfcManager.getTag()
} catch (ex) {
  console.info(ex)
} finally {
  await NfcManager.cancelTechnologyRequest()
}

console.log(tag.id) // Return the UID
```

**Comment by pke** [comment]
@cavasinf This also works with ISO tech on iOS
