### ISSUE TITLE
[ios] Attempted to register RCTBridgeModule class NfcManager for the name 'NfcManager'

### ISSUE THREAD

**Issue by cworsley4** [whitedogg13/react-native-nfc-manager#70]
Any idea why this would happen on app load? I'm more of an android guy than ios so this is a little unfamiliar to me.
<img width="342" alt="nfc-manager-error" src="https://user-images.githubusercontent.com/1875169/43011850-847f2bf2-8bf9-11e8-823b-0904c021fb6d.png">

**Comment by whitedogg13** [comment]
Hi, I have found a similar one here: https://github.com/realm/realm-js/issues/350, it seems that the project linked both new / old version of some library.

Can you check your xcode project to see whether there's any duplicated libs been linked? It should look like this (see the highlighted NfcManager.xcodeproject on the left bottom corner) :
![image](https://user-images.githubusercontent.com/10307875/43046846-92c0d454-8e01-11e8-903c-d5a81b14f820.png)

Or, maybe you can try a fresh install to see whether the issue remains, ex:
```
react-native init MyTestProject
cd MyTestProject
npm install --save react-native-nfc-manager
react-native link react-native-nfc-manager
```

Thanks!
