### ISSUE TITLE
I get the payload data but cannot parse out the text. Please help,

### ISSUE THREAD

**Issue by themakerman** [whitedogg13/react-native-nfc-manager#71]
![screen shot 2018-07-24 at 2 04 32 pm](https://user-images.githubusercontent.com/14818804/43119817-89c728c2-8f4a-11e8-9c39-ed65b00e90fe.png)

**Comment by whitedogg13** [comment]
Hi, sorry for the late response.

From the screenshot, your ndef's `tnf` value is 2, which refers to TNF_MIME_MEDIA, and currently ndef associated with this `tnf` not supported by our NdefParser API yet.

I will try to add this feature when I'm available and keep you posted!

**Comment by themakerman** [comment]
no probz....great library mate

**Comment by whitedogg13** [comment]
Hi, just perform some quick survey regarding this.

Fully support TNF_MIME_MEDIA parsing isn't an easy task, so it might need to use a external library such as [node-mime](https://github.com/broofa/node-mime).

However for your particular case, it might be easier to simply use `fromCharCode` to transform the payload back to text. For example:
```
text = tag.ndefMessage[0].payload.reduce(
  (acc, byte) => acc + String.fromCharCode(byte), ''
)
// text will be `Was up\n'
```

Hope that helps!

**Comment by themakerman** [comment]
hmm thanks i'll try it out

**Comment by whitedogg13** [comment]
close it for now due to no further activity, please reopen if the issue persists!
