### ISSUE TITLE
Using iPhone as a NFC Tag

### ISSUE THREAD

**Issue by ngocnguyen09910060** [whitedogg13/react-native-nfc-manager#73]
Hello everybody,
I want build an mobile app, using iPhone as a NFC Tag, touch it on NFC Reader. NFC Reader can get data from iPhone. Can i do it ?

**Comment by whitedogg13** [comment]
Hi, the scenario you describe is not possible because iOS doesn't have API to act as NFC tag.

**Comment by whitedogg13** [comment]
Close due to no further activity
