### ISSUE TITLE
Support of Card Emulation API

### ISSUE THREAD

**Issue by paveldz** [whitedogg13/react-native-nfc-manager#79]
It would be great to have Card Emulation API (including Host-based card emulation) supported by this library.

**Comment by whitedogg13** [comment]
Thanks for proposing. I'll check it out and see whether it's feasible when available.

**Comment by hezhii** [comment]
Is there any progress？

**Comment by umutcetinkaya** [comment]
Is there any progress？

**Comment by umutcetinkaya** [comment]
Is there any progress？

**Comment by whitedogg13** [comment]
Hi @umutcetinkaya sorry for pending this feature for so long. currently we don't have plan for card emulation, since this is still an exclusive feature for Android.

**Comment by Zenyker** [comment]
Hi @whitedogg13, did you made the card emulation feature?

Thanks

**Comment by Zenyker** [comment]
I just need to duplicate the serial number in my phone, how can I do that?
Thanks
