### ISSUE TITLE
how to write NFC android package type

### ISSUE THREAD

**Issue by ibnumuntoha** [whitedogg13/react-native-nfc-manager#84]
if write type text is

`function buildTextPayload(valueToWrite) {
    const textBytes = strToBytes(valueToWrite);
    // in this example. we always use `en`
    const headerBytes = [0xD1, 0x01, (textBytes.length + 3), 0x54, 0x02, 0x65, 0x6e];
    return [...headerBytes, ...textBytes];
}`
how to write nfc tag type android package, so when i scan nfc tag from my device going to the apps
and how to write more than one data .
first data is text type, second is android package

**Comment by whitedogg13** [comment]
Hi, you can try the following example:

```javascript
import NfcManager, {Ndef} from 'react-native-nfc-manager'
...
let bytes = Ndef.encodeMessage([
    Ndef.textRecord("hello, world"),
    Ndef.androidApplicationRecord("my-app-pkgname"),
]);

NfcManager.requestNdefWrite(bytes)
    .then(() => console.log('write completed'))
```

Thanks!

**Comment by ibnumuntoha** [comment]
hi, it's worked ,
thank you for your help
