### ISSUE TITLE
Write again on readOnly writed tag

### ISSUE THREAD

**Issue by dvdcsc** [whitedogg13/react-native-nfc-manager#89]
Is possible to erase tag writed with readOnly option?
I need to write the tag again in the case the content written was wrong
Please i need any help as soon as possible

**Comment by svvitale** [comment]
Once the read-only bit is written on an NFC tag, it can't be unwritten or overwritten.  It's part of the spec, not related to the software implementation.

**Comment by dvdcsc** [comment]
ok, thanks for the quick answer
