### ISSUE TITLE
NfcManager.start doesn't properly remove the iOS event listener. 

### ISSUE THREAD

**Issue by clickclickonsal** [whitedogg13/react-native-nfc-manager#9]
I created an NFC Screen & I've decided to initialize the NFC when I navigate to it. In my componentDidMount function I have the code shown below.
```
componentDidMount = () => {
    NfcManager.start({
      onSessionClosedIOS: () => {
          console.log('session closed');
          this._stopDetection();
          this.props.navigation.goBack();
       },
    });
};
```
This works just fine the first time around. I'll navigate to the screen, then on cancel it'll take me back, then I'll navigate to the screen again & when I click cancel I get the following error message. 
![image](https://user-images.githubusercontent.com/8260678/32736024-735a1fde-c864-11e7-9864-f081cfb5b6bf.png)

I took a look at the source code & found that the issue is that `Events.SessionClosed` event listener is being removed properly. So I've submitted a pull request #8 with a fix for this. :-)

**Comment by whitedogg13** [comment]
Hi, thanks for spotting the issue!
The PR is modified a little and already merged.
