### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by Rexima** [whitedogg13/react-native-nfc-manager#93]
I got this error:
![image-1](https://user-images.githubusercontent.com/7590208/46570764-e6755b80-c969-11e8-801b-e8d9a45aa5e2.jpg)

I just installed it with this command: **yarn add react-native-nfc-manager**
And put this line on my js file: **import NfcManager, {Ndef, NdefParser} from 'react-native-nfc-manager'**

**Comment by whitedogg13** [comment]
Hi, when using `expo` (or `create-react-native-app`) with this library (or any library with native dependency), you will have to:

* first `eject`, to restore correct project structure with native support
* `react-native link react-native-nfc-manager` to link the native dependency

Thanks!

**Comment by Rexima** [comment]
So i cannot use this with Expo?
I ejected it and than linked it, but it doesnt work, got the same error.

**Comment by whitedogg13** [comment]
Hi, it should work with Expo. Please check #38 , which is also using Expo and reported to work.

I am personally not using Expo, but I will try that with this lib when I'm available. 

Thanks!
