### ISSUE TITLE
[Document] write a section about how to use this library with Expo

### ISSUE THREAD

**Issue by whitedogg13** [whitedogg13/react-native-nfc-manager#95]
Just a reminder, since many RN developers use `CRNA` or `Expo`, we should write a section to help them adapt this library.

**Comment by christanfoden** [comment]
Would love this, or just some pointers about how it could be achieved at a glance. 

We're developing an app that requires NFC and wish to combine this with expo but there isn't much info available. Would you have to export using expo kit for example as I don't think you can edit info.Plist in expo without ejecting?

**Comment by C0deMunk33** [comment]
I'm currently stuck with Expo, any hints?

![image](https://user-images.githubusercontent.com/13264637/50359013-6f874200-0518-11e9-87be-6772f61ec98c.png)

**Comment by whitedogg13** [comment]
@C0deMunk33 it seems that your expo project isn't successfully ejected, so the native module (`NativeNfcManager`) is still undefined. Maybe you can try this guide: 
* https://docs.expo.io/versions/v31.0.0/expokit/eject.

**Comment by whitedogg13** [comment]
@C0deMunk33 If you have any updates, please share with us!

**Comment by whitedogg13** [comment]
@C0deMunk33 Thanks for the solid information!

**Comment by whitedogg13** [comment]
close inactive issue

**Comment by troutgirl** [comment]
Do you still need a doc for this?

**Comment by whitedogg13** [comment]
Yes, I believe it will still be helpful. It you can provide a PR, I will be happy to accept that. Thanks!

**Comment by troutgirl** [comment]
Seems like it wouldn't be THAT hard to build a unimodule, which I think is the "right way" in Expo-think. I spoke to Brent from Expo team today and he said something like this is on their list but way down in priority. Thoughts?

**Comment by whitedogg13** [comment]
Hi @troelsh thanks for contacting with expo team. I think currently we still need to guide expo user to properly `eject` to use 3rd party native module like this. 

About expo's unimodule, since most connectivity features such as NFC or BLE are hardware related, and not required by most apps, it's a natural approach to exclude them. Maybe they can do something like `expo-connectivity-modules` to include these native connectivity features, which might benefit app developers targeting IOT or custom hardware related stuff.

**Comment by troelsh** [comment]
@whitedogg13  you mean @troutgirl right? :)

**Comment by troutgirl** [comment]
Ah, good point! I will make sure to emphasize ejecting properly and what
you can/can't do in managed vs Bare workflow.

**Comment by fr3fou** [comment]
any news?

**Comment by troutgirl** [comment]
Sorry for the delay, I had to switch from one library to another and it set
me back. Still working tho!

**Comment by fr3fou** [comment]
what library did you switch to?

**Comment by troutgirl** [comment]
Chirp.io!

**Comment by niravbhimani53** [comment]
Hi, any update on how to use `react-native-nfc-manager` libary with [Expo](https://expo.io/)?
